### ISSUE TITLE
handleOpenURL not called on Android warm start

### ISSUE THREAD

**Issue by pmmenneg** [EddyVerbruggen/Custom-URL-scheme#100]
I have a Cordova 5.1.1 project using the plugin, and while cold starts are calling the `handleOpenURL` function on start, it is not being called when the app is already running.

We have this in the index.html of our Ionic/Angular SPA:

    <script>
      var handleOpenURL = function (url) {
        alert("HANDLE!!!");
        var data = {
          destination: url
        };
        window.localStorage.setItem("appLink", JSON.stringify(data));
      };
    </script>

On cold start, the alert if fired and localStorage set; if the app is running - nothing. Using version 3.2.2 of the plugin.

**Comment by joydragon** [comment]
I have the same issue, I don't know how to treat the app load on warm start.
Did you find a solution for this?

**Comment by pmmenneg** [comment]
@joydragon bumping up the plugin version 3.2.4 fixed the issue for us, although this was not identified as being fixed in the CHANGELOG (as far as we can determine).

**Comment by EddyVerbruggen** [comment]
@pmmenneg you're right, but indeed it should fix your trouble.
