### ISSUE TITLE
query string values are lost in handleOpenURL

### ISSUE THREAD

**Issue by chanksheadspin** [EddyVerbruggen/Custom-URL-scheme#103]
We are trying to pass query string values to the app through a link opened in an e-mail. When we access the url from handleOpenUrl, it only is index.html the query string parameters are lost.

I think we found a way to fix this if you are using Xcode and can edit the controllers here:http://davehiren.blogspot.com/2013/05/passing-query-string-with-indexhtml.html

but how can we fix this if using phonegap build?

Thank you!

**Comment by EddyVerbruggen** [comment]
Hi, what do you want to change in the native code exactly? And have you tried passing the params in a different way, like myapp://param1/param2/etc

**Comment by chanksheadspin** [comment]
We have tried using:
myapp://param1
myapp://index.html?param1=test
myapp://

and all of the results are index.html from handleOpenURL is there a way we can allow parameters through?

Thank you!

**Comment by EddyVerbruggen** [comment]
So even if you send myapp://param1 you get handleOpenURL(theUrl) ---> theUrl is index.html? That's very very strange.

Can you perhaps send me your project?

**Comment by chanksheadspin** [comment]
Sure, what is the easiest way to send you the project?

**Comment by EddyVerbruggen** [comment]
mail eddyverbruggen at gmail dot com

Also, just to rule out the email link: can you try to click the same link from a webpage loaded in the device' webbrowser?
