### ISSUE TITLE
ionic ios sporadic firing of handleOpenUrl on cold start

### ISSUE THREAD

**Issue by ricktbaker** [EddyVerbruggen/Custom-URL-scheme#104]
I can't seem to get the handleOpenURL function to fire on ios reliably.   I have it in my index.html and it works fine if the app is already running.  However if I close the app, I can only get it to fire periodically, maybe 25% of the time, the rest of the time it's not firing at all.  

Anyone experienced this in ios?  I am using setTimeout with varying delays, but does not seem to improve the behavior at all.

**Comment by EddyVerbruggen** [comment]
Which version of cordova-ios is this?

**Comment by ricktbaker** [comment]
I'm closing this out because it appears it's related to our app...I just tested on a base ionic app and it's working as intended.

**Comment by smarbos** [comment]
@ricktbaker hey! im experiencing the same problem. Have you find the cause of your problem? Something to share?
Thank you anyways!
