### ISSUE TITLE
handleOpenURL vs onResume (listener)

### ISSUE THREAD

**Issue by yantsey** [EddyVerbruggen/Custom-URL-scheme#105]
I'm trying to store information on the phone when a user opens this app via URL. But when the app is opened from URL, the onResume function (built in listener) is triggered BEFORE the LaunchMyApp is called. The problem I'm trying to do something in onResume that needs the information from the URL, but that information is not yet set.

How can I solve this problem? To clarify, onResume is in js/index.js, handleOpenURL is in js/plugins/LaunchMyApp.js

**Comment by EddyVerbruggen** [comment]
Perhaps add a `setTimeout` in your `onResume` handler.

But this is an architectural question about your app not about the plugin. You're better of asking this type of questions at StackOverflow.

**Comment by alanbuzdar** [comment]
noice
