### ISSUE TITLE
handleOpenUrl not called with cordova ios 3.8.0

### ISSUE THREAD

**Issue by dcartwright** [EddyVerbruggen/Custom-URL-scheme#106]
I'm having trouble getting this plugin to work. The steps don't seem very complicated, so I'm having trouble figuring out where I might be going wrong. My app uses angular, but I'm putting my handle function in the HEAD outside of any angular code. Here were my steps:

1. `cordova plugin add https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git --variable URL_SCHEME=edgedmo1501devdana`
2. Add the following to the `<head>` of my index.html file:
```
    <script>
        function handleOpenURL(url) {
            console.log("received url: " + url);
        }
    </script>
```
3. `cordova run ios`

If I visit Safari with the app running (this is in the iPhone 6 simulator), and type the URL `edgedmo1501devdana://home`, iOS pops up asking me if I want to open this URL in my app. When I confirm, the app comes up. However, nothing is logged to the console. I've also tried setting a break point and doing an alert inside of setTimeout. Nothing seems to be working. I've done lots of web searching and tried various approaches, but I think I'm out of debug steps to try - any thoughts?

By the way, the behavior does not change if I use the URL to cold start the app vs. already having it running. Also, I see in Safari Web Inspector that LaunchMyApp.js is being loaded successfully (although it's just the iOS placeholder comments).

`cordova platform list` tells me I am running ios 3.8.0. I just installed the plugin today, so it would be the most recent version as of the time of this writing.

**Comment by EddyVerbruggen** [comment]
Do you also have `cordova-plugin-console` installed?
And there is no CSP blocking inline scripts?

**Comment by dcartwright** [comment]
CSP might be it, I am using this one that I copied from a suggestion for the cordova-app-loader plugin, I honestly don't know how to interpret it as far as inline scripts:

`<meta http-equiv="Content-Security-Policy" content="default-src * 'self' cdvfile://*; style-src 'unsafe-inline' 'self' cdvfile://*; script-src 'self' 'unsafe-eval' cdvfile://*">`

**Comment by EddyVerbruggen** [comment]
Kick out that meta tag and try again :)

**Comment by dcartwright** [comment]
Well, if I kick out the meta tag my app won't load at all, but yes that's my plan. I'm away from my dev machine at the moment, I will try throwing the function in an external file and loading it in the <head> instead when I get in tomorrow, and let you know.

**Comment by EddyVerbruggen** [comment]
That should work; the CSP doesn't allow inline script (like the `handleOpenURL` function in your header), but throwing it in a .js file and loading that file in the head should work just fine.

It's a common problem ppl run into since the cordova cli added the whitelist plugin by default ;(

**Comment by dcartwright** [comment]
OK, makes sense. Should I rename this issue to something involving CSP to make it easier for the next person to find?

**Comment by EddyVerbruggen** [comment]
Not a bad idea ;)
