### ISSUE TITLE
Not Working. Cordova or Ionic blank project

### ISSUE THREAD

**Issue by gauravgaikwad777** [EddyVerbruggen/Custom-URL-scheme#109]
Steps to reproduce, running latest cordova, npm, node and android API 22 Nexus 6
1) cordova create hello com.example.hello HelloWorld
2) cd hello
3) cordova platform add android
4) cordova plugin add cordova-plugin-customurlscheme --variable URL_SCHEME=mycoolapp
or 
cordova plugin add https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git --variable URL_SCHEME=mycoolapp
5) cordova run android   // on genymotion Nexus 6 API 22 or Nexus 6 physical device 5.1
6) open browser and type "mycoolapp://"
7) Did not opened the app

Note:
-Tried ionic as well, same issue
-Tried on 3 different machines
-Works with Mac + iOS

**Comment by EddyVerbruggen** [comment]
Could you try opening a link from a mobile website on Android?

**Comment by gauravgaikwad777** [comment]
Added On both apps, ionic as well as cordova to cross reference
            <a href="mycoolapp://">Open mycoolapp://</a>
            <a href="hrcloud://">Open hrcloud://</a>

No response still

![screenshot_2015-09-10-01-56-02](https://cloud.githubusercontent.com/assets/8176450/9784328/66f7700c-575f-11e5-86d1-e2dcaa720d5b.png)
![screenshot_2015-09-10-01-56-10](https://cloud.githubusercontent.com/assets/8176450/9784329/69f32562-575f-11e5-89a4-023e6a1ca434.png)

**Comment by EddyVerbruggen** [comment]
Can you also try a webpage?
You may need to whitelist those URL's.

Also, can you see the scheme being added to your AndroidManifest.xml?

**Comment by gauravgaikwad777** [comment]
tried all three suggestions.
Also tried manually adding them.

Project link:
https://drive.google.com/file/d/0B0rPnF--M5UzMHRkbmw0bEhqMWc/view?usp=sharing

**Comment by EddyVerbruggen** [comment]
Just tried your hello project. All fine, see screenshot.

Can you try one of the mycoolapp:// links here?
http://www.x-services.nl/launchmyapp.php

**Comment by gauravgaikwad777** [comment]
Link or button works to open link, but my task is to open the app through link in browser which detect if my app is installed then go to app else continue on web.
This flow works perfect in iOS.

**Comment by EddyVerbruggen** [comment]
So your original issue (app doesn't open on Android) is resolved?

You browser can't detect if an app is installed, you just need to try it by having the user click a link.

**Comment by gauravgaikwad777** [comment]
Thanks @EddyVerbruggen 
This was a great help
