### ISSUE TITLE
Combine ios and android into a single LaunchMyApp.js

### ISSUE THREAD

**Issue by jason-engage** [EddyVerbruggen/Custom-URL-scheme#114]
Is there a way I can have a single LaunchMyApp.js file with some code that checks for the OS version? Otherwise, I have to switch the files in between of each build? I know its fairly trivial, but I have to build a lot of apps and I don't want to accidentally forget!

**Comment by jason-engage** [comment]
Should I just wrap this around the android version of the js? And it will work for both since iOS version is blank?

if ( (navigator.userAgent.match(/Android/i)) == "Android") {
}

**Comment by EddyVerbruggen** [comment]
Nooooooo - that's what plugman does for you; it injects the correct .js file when preparing the plugin for each platform. Simply use the CLI tooling and you're good.

**Comment by jason-engage** [comment]
I've never used plugman before, do I just call plugman install --platform ios --project platforms/ios --plugin cordova-plugin-customschemes ? and then I can forget about it?

**Comment by jason-engage** [comment]
Btw, I just checked my plist file and this is what i found: 

      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>vftest</string>
        </array>
      </dict>
    </array>

**Comment by EddyVerbruggen** [comment]
I'd use the Cordova CLI:

```
cordova create myproject
cd myproject
cordova platform add ios
cordova plugin add cordova-plugin-customurlscheme --variable URL_SCHEME=mycoolapp
cordova [prepare | build | run]
```

Those duplicate entries are a bug (not of this plugin), you can safely ignore or remove the duplicates.

**Comment by jason-engage** [comment]
Ya that's what I did. So when I run cordova build it will automatically choose the right JS file and inject it into /js/ for me?

I'm deleting the dupe entries, but they seem to have started after I installed this plugin. I'll try removing and re-adding it.

**Comment by jason-engage** [comment]
The dupe happens everytime i run 'ionic build ios'
