### ISSUE TITLE
LaunchServices: ERROR: There is no registered handler for URL scheme

### ISSUE THREAD

**Issue by softBarbarian** [EddyVerbruggen/Custom-URL-scheme#115]
@EddyVerbruggen thnaks for the great work. 
for some reason i am getting following error
`MobileMail[173] <Warning>: LaunchServices: ERROR: There is no registered handler for URL scheme frock`
i installed the blugin and successfully built the app but the app is not launching. Any pointers on what to check?

```
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 6.3.2 Build version 6D2105 

```

**Comment by EddyVerbruggen** [comment]
That's probably on an iOS9 device? You need to whitelist any urlscheme you want to launch from your app in your .plist file, so in your case:

```xml
<key>LSApplicationQueriesSchemes</key>
<array>
  <string>frock</string>
</array>
```

**Comment by softBarbarian** [comment]
@EddyVerbruggen upgraded to ios9 and added the key that you mention above to frock-Info.plist and now getting different error:
```
Sep 22 17:55:37 OKIP Evernote[2758] <Warning>: -canOpenURL: failed for URL: "frock://product/alksdjffjhjklahdsflkj" - error: "(null)"
```

any pointers?
