### ISSUE TITLE
handleOpenURL() function not firing for iOS/Phonegap Build

### ISSUE THREAD

**Issue by redbird19** [EddyVerbruggen/Custom-URL-scheme#116]
I use Phonegap Build, and I'm not sure what happened, things used to work, but I recently updated my app to change a completely unrelated ui issue, and now the handleOpenURL() function is not firing.  I verified that the new version of my app still works for Android, just not iOS.  

The change I made to my app was literally a few lines of css code, so there's no way it should have impacted this plugin.  Any ideas?

**Comment by EddyVerbruggen** [comment]
Have you changed the Cordova version perhaps? Which Cordova-iOS version are you on?

**Comment by redbird19** [comment]
Hi, nope haven't changed versions.  My config.xml file for phonegap build hasn't changed and is still using 3.7.0 version of phonegap:

<preference name="phonegap-version" value="3.7.0" />

My iPhone I'm testing with is iOS 8.4.

**Comment by redbird19** [comment]
Some new info...testing shows that handleOpenURL() IS called if my app is already open in the background, but not when my app needs to be launched.  Again, this is only the iOS version, the Android version works fine regardless if  the app is already open or not.

**Comment by EddyVerbruggen** [comment]
[See all these issues](https://github.com/EddyVerbruggen/Custom-URL-scheme/search?q=3.7.0&type=Issues&utf8=%E2%9C%93) and the warning at the top of the readme.

**Comment by redbird19** [comment]
Thanks for all your help and hard work on this plugin.  Sorry about re-hashing an old/known problem.

**Comment by ils-mrunalij** [comment]
Please help me regarding this..As handleOpenURL function does not call In my iOS device so I am unable to get the url..It is just opening the app.Its properly working in Android platform, I am doing this In Ionic project.
