### ISSUE TITLE
ERR_UNKOWN_URL_SCHEME on Android 5.1.1

### ISSUE THREAD

**Issue by emwalters** [EddyVerbruggen/Custom-URL-scheme#117]
Even though this plugin works for me on iOS 8, Android 4.4.2, and as a Windows 8.1 app, I'm having an issue with Android 5.1.1

On Android 5.1.1 using Cordova 5.0.0, when I try to access my application's custom URL scheme via an HTML anchor tag, I get this error:

Webpage not available

The webpage at foo://params could not be loaded because:

net::ERR_UNKNOWN_URL_SCHEME

Here's how I'm adding the plugin:

cordova plugins add cordova-plugin-customurlscheme --variable URL_SCHEME=foo

Here's how my anchor tag is set up:

    <a href="foo://params">click here to launch application<a>

**Comment by EddyVerbruggen** [comment]
Hi, where's that anchor located (another app?) - perhaps you need to whitelist it in config.xml?

**Comment by emwalters** [comment]
I put this line in the config.xml:

<allow-navigation href="foo:*" />

And I'm still getting the same error message.

I'm launching this link from the Android HTML Viewer.

**Comment by ericman93** [comment]
+1

**Comment by EddyVerbruggen** [comment]
@ericman93 Can you please provide details?

**Comment by ericman93** [comment]
Fixed it.
The problem was that the plugin was adding the *intent-filter* to the main activity.
So I added a new empty activity in the manifest and moved the *intent-filter* there.

**Comment by emwalters** [comment]
@ericman93  I modified my AndroidManifest.xml so that there is an empty activity that contains only the intent-filter. When I try to open the application using the custom URL scheme on an Android 4.4.2 tablet and it crashes my application. Can you post an example of what you did?  Maybe I'm missing something.

Here's how I set up my activity:

        <activity android:launchMode="singleTop" android:name="blank">
            <intent-filter>
                <data android:scheme="foo" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
        </activity>

**Comment by emwalters** [comment]
@ericman93 It also crashes on Android 5.0.2, which is technically a step forward because previously it wouldn't even try to open the custom URL scheme.

**Comment by emwalters** [comment]
Hey guys, I came up with a solution to the problem that fixes my issues on Android 4.4.2 and Android 5.0.2.  

Instead of putting the intent filter into an activity, I moved the intent-filter out from the activity to just under the application tag for my application.

Here's what my AndroidManifest.xml structure looks like now:
```xml
<manifest>
     <application>
        <intent-filter>
            <data android:scheme="foo" />
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
        </intent-filter>
        <activity>
        </activity>
     </application>
</manifest>
```
Perhaps the plugin should just drop the intent-filter in under the application as well?

**Comment by EddyVerbruggen** [comment]
@emwalters I appreciate the workaround of course, but it's not officially supported by Android if you look at [the docs](http://developer.android.com/guide/topics/manifest/intent-filter-element.html). It should be contained in an activity (or a few other tags), not in application. The manifest is a bit forgiving though so I can imagine it works.

Do you by any chance have more than one activity in your AndroidManifest.xml?

**Comment by emwalters** [comment]
Ah, I didn't realize that it wasn't officially supported.  

I do have more than one activity in the AndroidManifest.  I have four including the main activity.

**Comment by EddyVerbruggen** [comment]
I guess that's the problem - this plugin kinda expects only the default cordova activity, otherwise it will add the intent filter to probably the first activity it encounters.. Can you share your project perhaps?

**Comment by emwalters** [comment]
Here's my entire AndroidManifest.xml file:

```xml
<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="40000" android:versionName="4.0.0" package="com.foo.bar" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <application android:hardwareAccelerated="true" android:icon="@drawable/icon" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.Black.NoTitleBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <data android:scheme="foo" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
        </activity>
        <activity android:clearTaskOnLaunch="true" android:configChanges="orientation|keyboardHidden" android:exported="false" android:name="com.google.zxing.client.android.CaptureActivity" android:theme="@android:style/Theme.NoTitleBar.Fullscreen" android:windowSoftInputMode="stateAlwaysHidden">
            <intent-filter>
                <action android:name="com.google.zxing.client.android.SCAN" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        <activity android:label="@string/share_name" android:name="com.google.zxing.client.android.encode.EncodeActivity">
            <intent-filter>
                <action android:name="com.phonegap.plugins.barcodescanner.ENCODE" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        <activity android:label="@string/share_name" android:name="com.google.zxing.client.android.HelpActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
    </application>
    <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="22" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.FLASHLIGHT" />
    <uses-feature android:name="android.hardware.camera" android:required="false" />
</manifest>

**Comment by EddyVerbruggen** [comment]
Thanks, that makes sense - it's exactly what I get when installing the BarcodeScanner plugin and this one. The intent is added to the first activity indeed, the correct one. This still works on my 5.x devices though.

My cordova version is 5.4.1
My cordova-android version is 4.1.1 (`cordova platform list`)

**Comment by emwalters** [comment]
I just retested our original code and the custom URL functionality now works on Android 5.0.  I suppose it may have been a bug with Android that was patched or something.

In any case, thanks for looking into this!  Feel free to close the issue.
