### ISSUE TITLE
[Enhancement] Let the function name be configurable

### ISSUE THREAD

**Issue by pke** [EddyVerbruggen/Custom-URL-scheme#122]
To require the URL handler as a global function seems to make some problems in certain frameworks (ng, ionic) and its also bad style. How about putting the function name in the config and the plugin uses this instead of the hardcoded one it uses now?

Or use the cordova pubsub architecture to fire a "urlready" event.

If any of those is an option, I will prepare a PR

**Comment by celron** [comment]
I think you are talking abou handleOpenURL()... I thought handleOpenURL() is something that is defined on iOS, and that this plugin allows a "one-stop shop" for handling it on Android and iOS.

**Comment by EddyVerbruggen** [comment]
@celron exactly that.

**Comment by celron** [comment]
I believe that the cordova team is planning to make handleOpenURL() support into a plugin which might affect this plugin.

**Comment by pke** [comment]
> I believe that the cordova team is planning to make handleOpenURL() support into a plugin which might affect this plugin.

any news on that?
