### ISSUE TITLE
Gmail strips the href from the button in my HTML email template

### ISSUE THREAD

**Issue by bmwertman** [EddyVerbruggen/Custom-URL-scheme#123]
I have not been able to get my app to launch directly from the email client(Gmail in my test case). 

I am using the Mailgun api to send email confirmation emails. In my Mailgun HTML template I CAN successfully link to a page on my server which then has the correct href scheme to launch the app. And when clicked the app launches. But this seems messy and exposes my ip and port in the browser.

 If I use the same href scheme directly in my Mailgun HTML template the button does nothing and opening the chrome inspector shows that there is no href on the anchor tag.

So my question is, is it possible to launch my app directly from chrome? And if so, although not directly related to the above. Can I add a json web token to the end of that href scheme that I can grab with the handleOpenURL helper function to send back to my server to mark the user's email as confirmed?

**Comment by brianscroggins24** [comment]
I'm wondering about this issue as well. So far I've had to redirect my app to Safari on the iPhone and them redirect it again from the server calling the custom url scheme. This solution has not worked most of the time so i'm looking for another one. If email clients strip the url scheme how this issue be resolved?

**Comment by gusleo** [comment]
For me, it's working to create seperate href
Example:
<a  href="my-app://deep-link"
    href="http://example.com/backup-link"
    href="my-app://deep-link"
>Link Text</a>

**Comment by gusleo** [comment]
any updated for this issue?

**Comment by skotturi** [comment]
any updates?

I'm using nodemailer to send a password reset link to the user which opens a view in my ionic/cordova app. Everything works on ios + mac-mail but gmail on android strips the href from my email. pasting the url into chrome performs a google search..

**Comment by EddyVerbruggen** [comment]
That's not something this plugin can change, right? I've found the only reliable way is redirecting to a webpage where the user can click a link.
