### ISSUE TITLE
URL Types parameter added multiple times

### ISSUE THREAD

**Issue by uerceg** [EddyVerbruggen/Custom-URL-scheme#124]
Hi. I have added your plugin to my Cordova app and every time I execute `cordova build ios`, resulting project's `Info.plist` always gets extra `URL Types` array entry.

In this screenshot I made some 3 changes in my code and after each one of them I did `cordova build ios` and I got 3 items in `URL Types` array with same scheme name I selected once I installed your plugin.

<img width="420" alt="screen shot 2015-10-29 at 13 47 09" src="https://cloud.githubusercontent.com/assets/1741635/10818671/c1713c74-7e43-11e5-87e2-b5d893a12122.png">

Is this how plugin should behave?

Thanks in advance for your answer.

**Comment by ghislaindurand** [comment]
Same problem : at each build on ios, a new entry is appended in the plist array
(i don't have this problem on android)

**Comment by EddyVerbruggen** [comment]
This has been reported 6 times now - see https://github.com/apache/cordova-lib/pull/256
