### ISSUE TITLE
URL query not being passed to app

### ISSUE THREAD

**Issue by seesoe** [EddyVerbruggen/Custom-URL-scheme#125]
I've used this great plugin for over a year with no issues. Just recently a user pointed out that the feature is not working anymore. the app opens based on `myapp://testing123` but testing123 gets stripped out and i can never read it from the app.

even with basic stripped down code like this, i just get back `myapp://` (used to work). this is with iOS 9.1

```js
function handleOpenURL(url) {
  setTimeout(function() {
    alert("received url: " + url);
  }, 0);
}
```

**Comment by EddyVerbruggen** [comment]
Thanks, taking a look tomorrow!

**Comment by seesoe** [comment]
i just created a blank cordova project and i was able to read the query string. perhaps i need to move things around or adjust timeout timing?
