### ISSUE TITLE
Error when building with PhoneGap Build

### ISSUE THREAD

**Issue by papasmurph** [EddyVerbruggen/Custom-URL-scheme#128]
When building with PhoneGap Build I get the error below for Android when the plugin is included. Once it actually worked, but no more, without any change, so I first suspected a problem in PGB.

Secondarily (and not very important for my scenario), handleOpenUrl never fires. Don't I need to register a callback first?

Cheers,
Anders

Error: Project contains at least one plugin that requires a system library. This is not supported with ANT. Please build using gradle.
    at /project/cordova/lib/build.js:183:27
    at _fulfilled (/project/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/project/cordova/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/project/cordova/node_modules/q/q.js:760:13)
    at /project/cordova/node_modules/q/q.js:574:44
    at flush (/project/cordova/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

**Comment by EddyVerbruggen** [comment]
The error says one of the included plugins requires your project to be built with Gradle. This plugin doesn't so it must be a different plugin that's causing the trouble.

Anyway, please use a newer Cordova version with PGB.

**Comment by papasmurph** [comment]
Yup. My bad. Another plugin had been updated (in a broken way) just when I added your plugin, so "1 + 1 became NaN". Everything is the very latest.

handleOpenUrl never fires though, but I saw other posts about that.

**Comment by papasmurph** [comment]
And it wasn't even a real error. That plugin now needed "<preference name="android-build-tool" value="gradle" />". Oh well. Case closed.
