### ISSUE TITLE
Trouble with singleTask.

### ISSUE THREAD

**Issue by afmeva** [EddyVerbruggen/Custom-URL-scheme#13]
Hi, I'm not able to get URL params with singleTask mode. LaunchMyApp is returning  error callback, seems getDataString() is null.

Can you tell me something about this?

Thanks!

Sorry for my english.

**Comment by benwingz** [comment]
Hey guys I don't know if it really related but you'll tell me.
I have issues to fire handleOpenURL function on IOS (cordova version 4.2.0) when my app isn't already lauched (version of the plugin I use 3.2.2).

**Comment by EddyVerbruggen** [comment]
@benwingz are you on cordova-ios 3.7 perhaps (it's not the same as the CLI version you reported)? Avoid it.

**Comment by benwingz** [comment]
It was that actually, I was on 3.7 for cordova-ios and 4.2 for cordova.
Anyway thanks for your quick response.
