### ISSUE TITLE
Opening another application

### ISSUE THREAD

**Issue by murliatdure** [EddyVerbruggen/Custom-URL-scheme#133]
While using cordova app to launch another cordova app and pass the parameters.

Source app having - InAppBrowser plugin
Target app having - InAppBrowser, Custom URL plugins

While launching the target app it opens the target app inside the source app rather opening as separate app.

Can you please assist for the same.

**Comment by piotrowski** [comment]
> While using cordova app to launch another cordova app and pass the parameters.

Code?

>  it opens the target app inside the source app

Define please. Screenshot?

**Comment by murliatdure** [comment]
SOURCE APP - 

![image](https://cloud.githubusercontent.com/assets/7137859/11774489/c6824cc6-a25b-11e5-95c5-d962fdff5980.png)

window.open('targetapp://', '_system')

TARGET APP - 

![image](https://cloud.githubusercontent.com/assets/7137859/11774484/b9011f00-a25b-11e5-9800-c98804437d12.png)

function handleOpenURL(url) {
  alert("received url: " + url);
}


Please find the screenshots - 
![screenshot_2015-12-14-12-09-50](https://cloud.githubusercontent.com/assets/7137859/11774517/fab6eec0-a25b-11e5-9dd4-59119d88fab5.png)
![screenshot_2015-12-14-12-09-55](https://cloud.githubusercontent.com/assets/7137859/11774519/ff7076fc-a25b-11e5-8a9c-cca69867f76a.png)
![screenshot_2015-12-14-12-10-02](https://cloud.githubusercontent.com/assets/7137859/11774520/0412a9b4-a25c-11e5-9c36-91eca46cda40.png)

**Comment by murliatdure** [comment]
Can you please assist how to handle the same?

**Comment by EddyVerbruggen** [comment]
Since you're using window.open, did you do `window.open = cordova.InAppBrowser.open;` as stated [in the offical doc](https://github.com/apache/cordova-plugin-inappbrowser#cordova-plugin-inappbrowser)?

**Comment by murliatdure** [comment]
Doesn't work with the same

**Comment by EddyVerbruggen** [comment]
Plz share your code on github or something similar so folks can take a look if the want.

**Comment by danielpflood** [comment]
I am having this problem as well, any help would be greatly appreciated.

**Comment by danielpflood** [comment]
I was able to get around this by adding 030_update_platform_config.js to my hooks/after_prepare directory which parses the config.xml and sets "android:launchMode" in AndroidManifest to singleTask.
