### ISSUE TITLE
Issues with handleOpenURL(url) when trying to open a page within the app

### ISSUE THREAD

**Issue by gmanikumar** [EddyVerbruggen/Custom-URL-scheme#137]
I have successfully setup a custom url signsrestaurantandbar:// and I'm trying to link signsrestaurantandbar://page.html to an internal page page.html within the app.

I'm trying with this function below.

function handleOpenURL(url) {
      var strValue = url;
      strValue = strValue.replace('signsrestaurantandbar://','');
      window.location.href = strValue + ".html";
  }

On clicking the link sent through my email, handleOpenURL(url) gets fired and it attempts to redirect to the page.html page, but a black screen appears in the app. On closing the app and clicking the same link again, handleOpenURL(url) does not get fired a second time.

If I'm doing something wrong, I apologize and would appreciate it if you could point me in the right direction.

**Comment by EddyVerbruggen** [comment]
Try with a '.' before 'html'

**Comment by gmanikumar** [comment]
Thanks for the response, but there is a '.' before the html. I also noticed that when I tried window.open function instead, the page loads, but without the headers from index.html. So not sure why window.location.href doesn't work. I can see that the redirect does occur, but the end result is just a blank page. Also, noticed that handleOpenURL(url) doesn't get fired the second time. It only gets fired once I open it right after installing the app. Any ideas?

**Comment by EddyVerbruggen** [comment]
I can only guess without getting my hands on your app..

**Comment by jessemonroy650** [comment]
@EddyVerbruggen the `whitelist` plugin is tripping up people trying to implement this plugin. This developer happened to post on SO and I caught it. The cause is `CSP`. It is working on some webview, but not others. See {my answer to him here](http://stackoverflow.com/a/34281420/3255670)

It appears *signsrestaurantandbar:* need to be added to the `CSP`. It would look like this:
```
<meta http-equiv="Content-Security-Policy" 
         content="default-src * signsrestaurantandbar:; 
                  style-src * 'self' 'unsafe-inline' 'unsafe-eval'; 
                  script-src * 'self' 'unsafe-inline' 'unsafe-eval';">
```

**Comment by EddyVerbruggen** [comment]
Aha, yeah that's blocking inline JS indeed, so an exception needs to be added. Let me link to that SO issue from the readme :+1:

**Comment by gmanikumar** [comment]
Thanks that worked, however, I'm still facing the issue of handleOpenURL(url) not getting fired. Basically, it fires after a fresh install and never fires after that no matter if the app is closed or open. I'm testing on Android.

@EddyVerbruggen is there an email I can send my files over to you?

Thanks again to both of you for the help!

**Comment by jessemonroy650** [comment]
@gmanikumar It is always best to put your files (app) on github. This way we can easily test (and reproduce) your issue.

**Comment by gmanikumar** [comment]
@jessemonroy650 and @EddyVerbruggen - I have added the files I'm working on here:
https://github.com/gmanikumar/Test-app

Thanks.
