### ISSUE TITLE
Plugin Breaks windows phone build

### ISSUE THREAD

**Issue by msegers** [EddyVerbruggen/Custom-URL-scheme#139]
Hi, I was/am using this plugin to add some improved handling for iOS and Android (I believe windows is not supported?)

Anyhow, adding this plugin totally wrecks windows builds. Whilst Cordova is being inited, the launcMyApp.js throws an exception (line 8) Windows is not defined.

Removing your plugin fixes this issue for me, which is a pity since it does increase the usability if I can re-open the app from the browser. (we do some things which require input in external services, then do a callback).

Any chance it might be fixed for WP to at least not break everything? Making it functional would be better though.

**Comment by EddyVerbruggen** [comment]
@nadyaA any idea perhaps?

**Comment by msegers** [comment]
If you need more info from me let me know, I can re-add the plugin if wanted.

adding

`        <script type="text/javascript">
            //this will be overwritten, but allows displaying of startup errors
            window.onerror = function myErrorHandler(errorMsg, url, lineNumber) {
                alert("Error occured: " + errorMsg + "\n url: " + url + "\n On line: " + lineNumber, {type:"error", append:true});//or any message
                return true;
            }
        </script>`

on top of the index.html helps with getting errors to show up

**Comment by msegers** [comment]
I've noticed I was building wp8. It does break for wp8 but not for the windows target.

Which is actually what I needed. So, closing this.
