### ISSUE TITLE
App not launching

### ISSUE THREAD

**Issue by Mjwanyama** [EddyVerbruggen/Custom-URL-scheme#141]
Hello,

I am currently implementing the custom-url-scheme plugin on phonegap build. I have added the plugin in my config.xml as follows:

    <gap:plugin name="cordova-plugin-customurlscheme" source="npm">
        <param name="URL_SCHEME" value="appname" />
    </gap:plugin>

I have the app installed in my phone but when i put input the following on the phone browser;

    appname://

It opens a google search page. What am i doing wrong/what do i need to add?

Kind Regards,

Michael Wanyama.

**Comment by Mjwanyama** [comment]
I have seen that it is not possible to test it from a browser. I am now using;

    <a href="appname://">Open my app</a>

in an email as explained here;

    Your app can be launced by linking to it like this from a website or an email for example

Still not working. Any assistance will be greatly appreciated.

**Comment by EddyVerbruggen** [comment]
Please share your project with us somewhere. Github would be nice.

**Comment by Mjwanyama** [comment]
Hey Eddy,

Thank you for your response. I cant  share the project,i can however share my config file.

Here it is;

     <?xml version='1.0' encoding='utf-8'?>
<widget id="com.tangazo.tumasenti" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0" xmlns:android = "http://schemas.android.com/apk/res/android" >
   
    <name>appname</name>
    <description>
       xxxxxxxxxxxxxxxxxxxxx
    </description>
    <author email="xxxxxxxxx" href="xxxxxxxxxxxxxxx">
        xxxxxxxxxxxxxxxxxxxxxxxx
    </author>
    
    <preference name="prerendered-icon" value="true"/>
    <preference name="permissions" value="none" />
    <preference name='phonegap-version' value='cli-5.2.0' />
    <preference name="orientation" value="default" />
    <preference name="target-device" value="universal" />
    <preference name="fullscreen" value="false" />
    <preference name="webviewbounce" value="true" />
    <preference name="prerendered-icon" value="true" />
    <preference name="stay-in-webview" value="false" />
    <preference name="ios-statusbarstyle" value="black-opaque" />
    <preference name="detect-data-types" value="true" />
    <preference name="exit-on-suspend" value="false" />
    <preference name="show-splash-screen-spinner" value="true" />
    <preference name="auto-hide-splash-screen" value="true" />
    <preference name="disable-cursor" value="false" />
    <preference name="android-minSdkVersion" value="7" />
    <preference name="android-installLocation" value="auto" />
    <preference name="SplashScreen" value="mySplash" />
    <preference name="SplashScreenDelay" value="5000"/>
    <feature name="debug-server" required="false" />
     <gap:config-file platform="android" parent="/manifest/application" >
        <application android:debuggable="false" />        
    </gap:config-file>
    

    <gap:plugin name="cordova-plugin-camera" source="npm" />
    <gap:plugin name="cordova-plugin-device" source="npm" />
    <gap:plugin name="cordova-plugin-device-orientation" source="npm" />
    <gap:plugin name="cordova-plugin-dialogs" source="npm" />
    <gap:plugin name="cordova-plugin-splashscreen" source="npm" />
    <gap:plugin name="cordova-plugin-vibration" source="npm"  />
    <gap:plugin name="cordova-plugin-whitelist" source="npm"/>
	

    <gap:plugin name="cordova-sqlite-storage" source="npm"/>
    <gap:plugin name="pushbots-cordova-plugin" source="npm" />    
    <gap:plugin name="cordova-plugin-barcodescanner" source="npm" />

    
        <gap:plugin name="cordova-plugin-customurlscheme" source="npm">
            <param name="URL_SCHEME" value="appname" />
        </gap:plugin>
  
  <gap:splash src="img/splash.png" /> 
    

    <icon src="img/icon.png" gap:role="default" />
    <icon gap:platform="android" gap:qualifier="ldpi" src="res/icon/android/icon.png" />
    <icon gap:platform="android" gap:qualifier="mdpi" src="res/icon/android/icon.png" />
    <icon gap:platform="android" gap:qualifier="hdpi" src="res/icon/android/icon.png" />
    <icon gap:platform="android" gap:qualifier="xhdpi" src="res/icon/android/icon.png" />   
    <icon gap:platform="ios" height="57" src="res/icon/ios/icon-57.png" width="57" />
    <icon gap:platform="ios" height="72" src="res/icon/ios/icon-72.png" width="72" />
    <icon gap:platform="ios" height="114" src="res/icon/ios/icon-57-2x.png" width="114" />
    <icon gap:platform="ios" height="144" src="res/icon/ios/icon-72-2x.png" width="144" />
    <icon gap:platform="webos" src="res/icon/webos/icon-64.png" />
    <icon gap:platform="winphone" src="res/icon/windows-phone/icon-48.png" />
   <icon gap:platform="winphone" gap:role="background" src="res/icon/windows-phone/icon-173.png" />
   
    <gap:splash gap:platform="android" gap:qualifier="port-ldpi" src="res/screen/android/mySplash.png" />
    <gap:splash gap:platform="android" gap:qualifier="port-mdpi" src="res/screen/android/mySplash.png" />
    <gap:splash gap:platform="android" gap:qualifier="port-hdpi" src="res/screen/android/mySplash.png" />
    <gap:splash gap:platform="android" gap:qualifier="port-xhdpi" src="res/screen/android/mySplash.png" /> 
    <gap:splash gap:platform="ios" height="480" src="res/screen/ios/screen-iphone-portrait.png" width="320" />
    <gap:splash gap:platform="ios" height="960" src="res/screen/ios/screen-iphone-portrait-2x.png" width="640" />
    <gap:splash gap:platform="ios" height="1136" src="res/screen/ios/screen-iphone-portrait-568h-2x.png" width="640" />
    <gap:splash gap:platform="ios" height="1024" src="res/screen/ios/screen-ipad-portrait.png" width="768" />
    <gap:splash gap:platform="ios" height="768" src="res/screen/ios/screen-ipad-landscape.png" width="1024" />
    <gap:splash gap:platform="winphone" src="res/screen/windows-phone/screen-portrait.jpg" />
  
  <allow-navigation href="*" />
  
  <access origin="*" />

    
    
    
</widget>

**Comment by Mjwanyama** [comment]
I am then sending this to myself via gmail so as to test it.

    <a href="appname://">Open my app</a>

**Comment by EddyVerbruggen** [comment]
Just to rule this out: did you try that link from a regular webpage? Please try it.

**Comment by Mjwanyama** [comment]
It worked perfectly from a webpage. Thanks Eddy.

For anyone who encounters the same problem,you need to create a webpage and try it from there. Trying from the browser or an email wont work.

Kind Regards,

Michael Wanyama.

**Comment by royipr** [comment]
@EddyVerbruggen  does this means that if I'm sending to my users an email with a link to the application myapp:// this wont work?

I really want my users to be able to open the app fro the mail im sending

**Comment by EddyVerbruggen** [comment]
Best practice imo is sending them to a website which has the link.
