### ISSUE TITLE
handleOpenURL is called after app.run()

### ISSUE THREAD

**Issue by royipr** [EddyVerbruggen/Custom-URL-scheme#142]
Hi all

Im trying to work with this plugin and i have encountered a strange issue:
the handleOpenURL is seems to be invoked after the application run()

I put the handleOpenURL function in my index.html in the head before loading any other script:

 `  <script>`
`   function handleOpenURL(url) {`
`     setTimeout(function() {`
`       localStorage.setItem("openURL", url);`
`      console.log("url seted");`
`     }, 0);`
`  }`
`   </script>`

And in my app.run function i did the next thing:

`rootModule.run(init);`
`init.$inject = ['$ionicPlatform', 'localStorageService', 'openUrlService'];`
`function init($ionicPlatform, localStorageService, openUrlService) {`
`  $ionicPlatform.ready(function() {`
`    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard`
`    // for form inputs)`
`    if(window.cordova && window.cordova.plugins.Keyboard) {`
`      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);`
`    }`
`    if(window.StatusBar) {`
`      StatusBar.styleDefault();`
`    }`
`    var openURLKey = "openURL";`
`    var openURL = localStorageService.get(openURLKey);`
`    if(openURL) {`
`      var url = localStorageService.get(openURLKey);`
`      console.log("Application opned with URL: ", url);`
`      openUrlService.handleURL(openURL);`
`      localStorageService.delete(openURLKey);`
`    }`
`  });`
`};`

Now When i run the app for the first time the `if` is not true..
and when clicking on the link the application open but still the `if` is false
only in the third time the if is true and i can handle the url..

I also put some console logs and it looks like the handleOpenURL is called after the init...
What am i doing wrong?

**Comment by EddyVerbruggen** [comment]
Not sure which platform you're referring to. I'm assuming Android since on iOS won't wait for deviceready to invoke `handleOpenURL`. [Android does](https://github.com/EddyVerbruggen/Custom-URL-scheme/blob/master/www/android/LaunchMyApp.js#L31), so you may run into a race condition if you wire it up like you did. Especially when wrapping it in a timeout.

How about moving making `window.handleOpenURL = function(url).. etc` available inside your `ionicPlatform.ready` function?

**Comment by royipr** [comment]
yes Im running it on Android.. and from what i understand the wrap with setTimeout is needed for ios no?
I also tried removing the setTimeout and its is still with the same behaviur

Moving the function inside the `ionicPlatform.ready` did the trick, but can i count on that solution? on both android and ios?
 and i should remove that function from the index.html right?

**Comment by EddyVerbruggen** [comment]
Great you have it working on Android. I'm sure you can find a way to make it work on both platforms.
