### ISSUE TITLE
App not launching from in-app browser

### ISSUE THREAD

**Issue by Mjwanyama** [EddyVerbruggen/Custom-URL-scheme#143]
I got the basic requirements of the app working. I realized that when i get out of my app to the webpage from which i launch back to the app,the app is using an in-app browser. This is due to the fact that the device browser isn't launched.

However,i noticed that if i paste the url in the device browser it works but from this in-app browser,it doesn't work. I have looked at documentation pertaining to CSP and also tried it. I have the following in my config.xml

    <allow-navigation href="*" />
  
    <access origin="*" /> 

Any ideas on what i need to do? 

Kind Regards,

Michael.

**Comment by EddyVerbruggen** [comment]
AFAIK you can't launch your app from inside your app. Why not launch the systembrowser?
