### ISSUE TITLE
Readme: Warn people about why iOS 9.2 deeplinks don't work

### ISSUE THREAD

**Issue by lorensr** [EddyVerbruggen/Custom-URL-scheme#144]
Most people have a webpage that tries to do `my-app://` with a timeout to the app store, but now this method always times out to the app store, so it's recommended that you switch to Universal Links

https://blog.branch.io/ios-9.2-redirection-update-uri-scheme-and-universal-links

**Comment by EddyVerbruggen** [comment]
Have you seen it not working with a link opened from a website? I just tested it and after the browser asking 'Open in _your app name_'? it opens my app.

Not sure what you'd like to have added to the readme, but I will review a PR of course.

**Comment by lorensr** [comment]
Yes, that's what I meant, sorry. 

The downside of that method is the error alert when you don't have the app installed.

**Comment by EddyVerbruggen** [comment]
Correct, that's why I'm using it by setting the target of the `<a>` tag to a hidden iframe. The alert gets swallowed by the iframe ;)

**Comment by lorensr** [comment]
That no longer works for me – the `Open in "mycoolapp"?` dialog is also swallowed, and the app is not opened. Are you able to get the dialog to show? This is what I was doing:

```coffeescript
  if is_ios
    frame = document.createElement 'iframe'
    frame.setAttribute 'src', 'mycoolapp://foo'
    frame.setAttribute 'style', 'display:none;'

    document.body.appendChild frame
```

**Comment by EddyVerbruggen** [comment]
Ah, yeah, you MUST click it now to launch the app whereas before there was no alert if the app was installed.

My code was quite similar (but I'm not maintaining that project anymore, so haven't heard of any trouble because of this).

Bummer. If you have a good suggention for the wording in the readme then I'm all ears.

**Comment by lorensr** [comment]
Suggested wording is in the pr 😉

**Comment by lorensr** [comment]
Oops, I apologize – looks like the PR didn't go through. Rebased and submitted: #157
