### ISSUE TITLE
Launching another app on Android

### ISSUE THREAD

**Issue by aneveucertify** [EddyVerbruggen/Custom-URL-scheme#146]
Hi! I am using PhoneGap Build, and have added this plugin to my config.xml file. I am able to launch another app on iOS with a simple window.open command and it works great, which is to say that the inappbrowser pops open and the other app gets launched if it is installed, and if not it goes to the app store. So far, so good! My problem is that the same window.open does not work properly on Android. There, I see the inappbrowser window and the location bar has the URL that I tried to open, but the app is not launched (it is installed). The inappbrowser just shows a blank page at that point.

I'm not entirely sure if I'm doing this right at all, and I don't really know if I even need this (awesome) plugin because I don't need for my app to be able to be launched - I just need to be able to launch other apps. Thoughts?

**Comment by EddyVerbruggen** [comment]
You're right, that's not what this plugin is for.
