### ISSUE TITLE
meteor-1.3-beta-2 url_schemes not firing anymore

### ISSUE THREAD

**Issue by rlech** [EddyVerbruggen/Custom-URL-scheme#147]
after a quick tryout it looks like the custom url scheme is not working anymore with ```meteor 1.3-beta2```.
first I thought it has something to do with the new server name (`meteor.local` is now `localhost:<random:ip>` and my routes get an ```404``` because they dont exist anymore but the events are not firing now.

I tried 2 code snippets (normally the first block was working for me but coldstart was not working) but still have no luck

```javascript
Meteor.autorun(function () {

    document.addEventListener('deviceready', function () {
        handleOpenURL = function handleOpenURL(url) {
            Meteor.defer(function () {
                console.log(url);
                window.location.href = url;
            });
        }
    });

});

//I tried also this code but also not firing anymore


Meteor.startup(function() {
  if (Meteor.isCordova) {
    window.plugins.launchmyapp.getLastIntent(function(url) {
      if (intent.indexOf('mycoolapp://' > -1)) {
        console.log("received url: " + url);
      } else {
        return console.log("ignore intent: " + url);
      }
    }, function(error) {
      return console.log("no intent received");
    });
    return;
  }
});
```

EDIT:

After thinking a bit more about it it also could be that it has something todo with the replacement of the `UIWebkit`. `meteor 1.3` is using `WKWebView` in the future because of better js performance. 

@EddyVerbruggen could it be the same problem like this issue?
https://github.com/Telerik-Verified-Plugins/WKWebView/issues/98

meteor 1.3beta-2 information:
https://github.com/meteor/meteor/issues/6050

**Comment by matthewyt** [comment]
How did you get this to work? I am still seeing the same issue on the newest version and 1.3-cordova-beta.5.
