### ISSUE TITLE
Meteor iOS window.plugins.launchmyapp.getLastIntent not defined

### ISSUE THREAD

**Issue by Chun-Yang** [EddyVerbruggen/Custom-URL-scheme#149]
I tried to follow the instruction https://github.com/EddyVerbruggen/Custom-URL-scheme#meteor. However `window.plugins.launchmyapp.getLastIntent` in my simulator browser console.

**Comment by EddyVerbruggen** [comment]
Hi, you're right - it wasn't clear that this was implemented for Android only. Do you have trouble on iOS as well (haven't heard of that yet).

**Comment by Chun-Yang** [comment]
@EddyVerbruggen The scheme works on iOS when the app is already opened. However when the app does a code start the `handleOpenURL` would not be called. Is this the expected behavior? Thank you!

**Comment by EddyVerbruggen** [comment]
I don't know since I'm not a meteor user.

**Comment by rlech** [comment]
It's also not working for me at cold start with meteor 1.2.1 on iOS 9.

**Comment by ensemblebd** [comment]
I don't understand, if `getLastIntent` is for android only (mentioned above), then IOS simply doesn't support it?
What is the "or" to the exception. 

It's like saying "that tire doesn't fit on your car", then both people just walk away instead of finishing the conversation.
