### ISSUE TITLE
Not working in latest cordova and os

### ISSUE THREAD

**Issue by sunojvijayan** [EddyVerbruggen/Custom-URL-scheme#150]
when i click on the button. it says

Refused to execute inline event handler because it violates the following Content Security Policy directive: "default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

if i remove the restrictions nothing is happening. Please help?

**Comment by EddyVerbruggen** [comment]
Please check SO or Google for this error - it's because of CSP..
