### ISSUE TITLE
http and https handling for Android

### ISSUE THREAD

**Issue by raymondelferink** [EddyVerbruggen/Custom-URL-scheme#151]
Hi Eddy,

I found this apparently abandoned fork that supports http and https deeplinks for android devices.

just a few small changes seem to do the trick:
https://github.com/machenmusik/LaunchMyApp-PhoneGap-Plugin/commit/9c6975bd7e4510f8425d748947911da047ae1d56

It's just that this fork has not been updated with your more recent code.

I would be very happy if your plugin would support this too! 
Is there any reason not to make these changes?

Cheers, Raymond

**Comment by raymondelferink** [comment]
ok, tried some more fiddling and I got it working for now by adding this at the end of my config.xml:

`<gap:config-file platform="android" parent="/manifest/application" mode="add">`
`        <activity android:name="[myappname]" android:label="@string/app_name">`
`            <intent-filter>`
`                <action android:name="android.intent.action.VIEW" />`
`                <category android:name="android.intent.category.DEFAULT" />`
`                <category android:name="android.intent.category.BROWSABLE" />`
`                <data android:scheme="http" android:host="[myurl]" android:pathPrefix="[/mypath]" />`
`                <data android:scheme="https" android:host="[myurl]" android:pathPrefix="[/mypath]" />`
`            </intent-filter>`
`        </activity>`
`</gap:config-file>`

I have this and your plugin now running side by side and all intents are picked up nicely!

**Comment by EddyVerbruggen** [comment]
👍 Just added something similar to this plugin through a PR.
