### ISSUE TITLE
ReferenceError: Can't find variable: url

### ISSUE THREAD

**Issue by oudj001** [EddyVerbruggen/Custom-URL-scheme#161]
Hi Guys,

First Eddy, good job! 

I'm having difficulties getting the handleOpenURL function to work. 
Running ionic app on iOS 
Cordova-ios version: ios-3.8.0

Getting the error on iOS device: ReferenceError: Can't find variable: url

In my app.js (first loaded script) i wrote this above all the angular code:
function handleOpenURL(url) {
    setTimeout(function() {
        console.log(url);
    }, 500);
}

Installed everything using NPM

What am i doing wrong? 

Thanks in advance!

**Comment by EddyVerbruggen** [comment]
That error doesn't make sense in relation to that code. If anything it should say 'undefined', but it surely can find that variable.. can you post your entire code perhaps?

**Comment by oudj001** [comment]
Eddy, your totally right. I made a fuckup somewhere else. Thanks for your time!

**Comment by EddyVerbruggen** [comment]
No worries :beers:
