### ISSUE TITLE
ionic state reset with "--variable URL_SCHEME=mycoolapp"

### ISSUE THREAD

**Issue by hasLoren** [EddyVerbruggen/Custom-URL-scheme#167]
I am trying to remove and add back platforms and plugins using `ionic state reset.`  It throws an error because it needs an option  ` "--variable URL_SCHEME=mycoolapp". `

Since it's re-adding back my plugins from my package.json when i run `ionic state reset`, how do i tell it to add that option?

``` 
/package.json

"cordovaPlugins": [
    "https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git",
   ......
  ],
  "cordovaPlatforms": [
    "ios" 
```

**Comment by JorritPosthuma** [comment]
Just for other people that have the same question, in your `package.json`:

```
  "cordovaPlugins": [
    {
      "variables": {
        "URL_SCHEME": "yourappid"
      },
      "locator": "cordova-plugin-customurlscheme",
      "id": "cordova-plugin-customurlscheme"
    }
  ]
```

**Comment by rahulbpatel** [comment]
+1
