### ISSUE TITLE
custom-url-schem not recognizes link in sms

### ISSUE THREAD

**Issue by allicon** [EddyVerbruggen/Custom-URL-scheme#172]
i send a sms including a link with a custom-url-scheme mycoolapp:// but android did not recognize it as link. So i am not able to click it.

When i click a html link like <a href='mycoolapp://' >link</a> it works fine and opens the app.

Do you have a hint how i can make it work?

**Comment by Grantlyk** [comment]
Android has done this on purpose,

Off the top of my head, the best solution in my eyes would be to sms a link to a webpage that redirects the user to the desired url scheme
