### ISSUE TITLE
Not working on gmail

### ISSUE THREAD

**Issue by subhash8108** [EddyVerbruggen/Custom-URL-scheme#175]
Hello,

I'm checking on mobile.
I have create link setup on http://easyhyperlinks.com for testing purpose. 
Its perfectly working, apps open very smoothly.

But not working on gmail... please help me

My code:
<a title="Game" href="playecology://game/id/28">Gamel Link</a>

gmail not allow without http so this link not create... please help me

Thanks & Regards
Subhash Patel

**Comment by EddyVerbruggen** [comment]
Can you post that code (again)?

**Comment by subhash8108** [comment]
My code:
<\a title="Game" href="playecology://game/id/28">Gamel Link<\/a>

**Comment by EddyVerbruggen** [comment]
Markdown tip: you can use \`backticks\` to escape code and properly format it: `<a title="Game" href="playecology://game/id/28">Gamel Link</a>` 👍 

This is totally up to the Gmail app, so not much I can do to change this. The most reliable solution for me has always been linking to a webpage from an email and opening the app from that webpage.

**Comment by subhash8108** [comment]
When i set proper format then not showing hyperlink code..

`<a title="Game" href="playecology://game/id/28">Gamel Link</a>`

this link not working in gmail

**Comment by EddyVerbruggen** [comment]
If the tinyurl works then I guess it's a permission thing. That's a great workaround btw!

**Comment by subhash8108** [comment]
allow all permission.

**Comment by subhash8108** [comment]
i have set `<a title="Game" href="playecology://game/id/28">Gamel Link</a>`, If not getting this url then i should go play store... am i right?
