### ISSUE TITLE
Update Plugin

### ISSUE THREAD

**Issue by trumpet2012** [EddyVerbruggen/Custom-URL-scheme#178]
@EddyVerbruggen,

First of all I would like to thank you for writing this plugin, it has been tremendously helpful. I was going through and testing the plugin on Windows and I noticed that the app manifest is not being updated for Windows 10. I can see that you have fixed this on the master version of the code, but the cordova plugin repository has need been updated to the newest version.

I plan on just installing the plugin from github for now, but just wanted to make sure you were aware.

Thanks!

**Comment by EddyVerbruggen** [comment]
Hi!

I was sitting on this version a bit because of a few changes I wasn't 100% sure of they would work correctly, but I guess it's time to tag 4.2.0 and push it to npm.

Cheers,
Eddy
