### ISSUE TITLE
Plugin name confusion needs explaination

### ISSUE THREAD

**Issue by pke** [EddyVerbruggen/Custom-URL-scheme#183]
how is this plugin called now officially? `launchmyapp` or `custom-url-scheme`?

The docs mention `launchmyapp` yet the repo is called `custom-url-scheme`

**Comment by EddyVerbruggen** [comment]
It used to be `launchmyapp` and is now `custom-url-scheme`. Send a PR if you think things can be cleaned up.

**Comment by pke** [comment]
Here you go #185
