### ISSUE TITLE
Plugin should add URL_SCHEMA as whitelist intent to config.xml

### ISSUE THREAD

**Issue by pke** [EddyVerbruggen/Custom-URL-scheme#184]
According to a [stackoverflow](http://stackoverflow.com/questions/34257097/using-handleopenurl-with-custom-url-scheme-in-cordova/34281420#34281420) posting one needs to add

`<allow-intent href="mycoolapp:*" />`

to the config when using the whitelist plugin to ensure the app url can be called from within the app.

So this plugin should add the `URL_SCHEMA` variable to the manifest

**Comment by EddyVerbruggen** [comment]
Can you link to the post please?

**Comment by pke** [comment]
@EddyVerbruggen updated the OP

**Comment by EddyVerbruggen** [comment]
Reading the SO post I think this is not needed. You require `<allow-intent href="mycoolapp:*" />` if you want to invoke `mycoolapp://` from your app, but not for receiving links to your app.

Did you verify that it's required?

**Comment by pke** [comment]
That's why I wrote in my OP: 
>  to ensure the app url can be called from within the app.

But maybe my app use case is to special to generalise that for every user. I'll close therefor and remark this in our internal wiki instead.
