### ISSUE TITLE
Why isn't URL_SCHEMA a normal preference but a plugin variable?

### ISSUE THREAD

**Issue by pke** [EddyVerbruggen/Custom-URL-scheme#186]
Since its not a `config.xml` preference its very difficult to change the schema once you've added the plugin to your app. That is because for reasons unkown to me cordova writes the variable to the `app/plugins/<platform.ini>` file like this:

```
"cordova-plugin-customurlscheme": {
            "URL_SCHEME": "mycoolapp",
            "ANDROID_SCHEME": " ",
            "ANDROID_HOST": " ",
            "ANDROID_PATHPREFIX": "/",
            "PACKAGE_NAME": "app.id"
        }, 
```

If URL_SCHEME would be a normal `config.xml` preference like this:

`<preference name="URL_SCHEME" value="mycoolapp" />`

It could be easily changed and only a small change in `plugin.xml` is needed to make this work.

At the moment, the only way to change the URL schema is to remove the plugin and re-add it to the app.

**Comment by EddyVerbruggen** [comment]
[But it is, right?](https://github.com/EddyVerbruggen/Custom-URL-scheme/blob/master/plugin.xml#L24)

**Comment by pke** [comment]
I wondered that too when inspecting the `plugin.xml`. How come it is not added as a preference in the config by the plugin (hook after_install)? 
How do variables and preferences relate in cordova? 

Because I verbatim copied this readme's line of how to install the plugin and of course it ended up setting the `URL_SCHEME` variable to `mycoolapp`. Changing that without re-installing the plugin seemed impossible to me.

**Comment by pke** [comment]
@EddyVerbruggen is it possible to change the plugins preference URL_SCHEME in `config.xml` and have cordova pick up this change?

**Comment by adityasaxena** [comment]
@pke Not sure what you mean but I set URL_SCHEME in config.xml as follows and it works fine:

```
<plugin name="cordova-plugin-customurlscheme" spec="~4.2.0">
        <variable name="URL_SCHEME" value="myurlschemegoeshere" />
</plugin>
```

**Comment by pke** [comment]
so variables and preferences are interchangeable?

**Comment by adityasaxena** [comment]
@pke I don't know, but from what I know so far, I believe them to be different.

A preference is something that goes in a platform and is probably goes into AndroidManifest.xml or *.plist file depending upon the platform (Android/iOS)

A variable, instead, seems to be something which is associated with a plugin (as in this plugin), and then it is upto plugin.xml file of the plugin to attach that behaviour to the platform as needed.

In any case, your question about _configurable urlscheme_ does have an answer. You can actually set customurlscheme in config.xml and rely on your config.xml to get the right configuration show up in your builds everytime.

**Comment by pke** [comment]
This is confusing still.

**Comment by adityasaxena** [comment]
@pke Sorry. I think I'm confused what you're asking as well. 
Maybe you're asking about how cordova config.xml fundamentally works. 
Maybe you're asking about how this plugin does or does not comply with how config.xml fundamentally works.

Maybe @EddyVerbruggen can explain.

**Comment by pke** [comment]
Closing this as stale.
