### ISSUE TITLE
"Open in" apple devices

### ISSUE THREAD

**Issue by kodatech** [EddyVerbruggen/Custom-URL-scheme#193]
Hi there,

I'm not sure if it is an issue but in apple devices when I click the URL scheme link always ask "Open in nameApp?" It is not a real problem but I think should be better if don't ask. Anybody knows how to solve this?

Tks,

**Comment by EddyVerbruggen** [comment]
That's the OS kicking in, nothing can be done about that. Fortunately every app has this problem.
