### ISSUE TITLE
stopped working on IOS 9.3.5

### ISSUE THREAD

**Issue by kimras** [EddyVerbruggen/Custom-URL-scheme#200]
Hi,
I have been using this fantastic plugin, but today i found that it is not working on iOS anymore after a update. 
I am using Phonegap Build, and have not done any changes to the settings for the last year or so.

Can anyone confirm if you have it working on iOS 9.3.5 ? And if I need to do more than just this in teh Config.XML.

	<plugin name="cordova-plugin-customurlscheme" source="npm">
		<param name="URL_SCHEME" value="xxxxxx" />
	</plugin>

Thanks in advance
Kim

**Comment by EddyVerbruggen** [comment]
Hey @kimras I saw you posting something similar in the universal links plugin issue tracker.. what have you found in the meanwhile? Any idea why you're seeing this issue?

**Comment by EddyVerbruggen** [comment]
Btw, just tested on iOS 9.3 sim, iOS 10 sim, iOS 10 device. Both warm and cold launches from a custom url scheme seem to work fine..

**Comment by kimras** [comment]
First of all thanks for trying it out. My experience is that it stopped working with the 9.3.5 or 9.3.4 , But did work perfectly in older version. I assume it was removed with the big security update they did.. 
My current build is Cordova iOS 4.2 but it was occurring after I released my previous build that did use 4.1.1.
I am sure it is a iOS patch that broke my app. I had a release done start of August which did work, but it stopped working some time last week. What i am not sure of is if it is 9.3.4 or 9.3.5 as my test device might not have been fully patched.

As for the universal-link have I not found any workaround yet.. but will update you if I get a break through..

Thanks again

**Comment by yurish** [comment]
Got the same issue. Stopped working since 9.3.5.

**Comment by kimras** [comment]
I can confirm that that also is the case here, I can not redirect from a http or https site, I can not scan directly as a QR (Could be the scanner not accepting the Custom Schema), but if I type in the url into Safari it opens the app..
So question is if it can be controled with some king of certificate of security setting on the Site.

**Comment by yurish** [comment]
I found out, that redirecting with JavaScript works. Try using window.location="myapp://".

**Comment by kimras** [comment]
OK - So moving forward, I do have a WEB site that reroutes using the above method. 
I need to start the App with a GUID so everything revolves around QR-scanners.. And it actually looks like it is the QR-Scanner that can not launch the site. If I cut and paste the Url read from the QR-Scanner into Safari it does start the App just as before 9.3.5. It explains some thing but just make it more complicated as this is now involves yet another component :-)

So now the question is what changed that made standard QR-scanners not working. And maybe the workaround would be to re-rute to Safari with the URL from the QR-Scanned web call, can that be done ?

PS: My current work around is that I have included a QR-Scanner into the app.. But i like a more smooth user experience.

**Comment by kimras** [comment]
OK - Last update for now..
I have found some QR scanners that works.. So I can confirm that is is the QR scanner..
This one works      : QR Code Reader by Scan
This one does not : QR Reader for iPhone by TapMedia Ltd.

Eddy.. Thanks fro allowing us to discuss this on your issue, and Thanks for a fabulous Plugin..
