### ISSUE TITLE
Broken in iOS 10

### ISSUE THREAD

**Issue by PabloPerezAdsuar** [EddyVerbruggen/Custom-URL-scheme#202]
Hi, 

I am using this plugin for a long time without problems, however, from the update to iOS 10 does not work.

My code is:
`window.open("apptest://","_self");`

Would you happen to someone else?

Thank you

**Comment by PabloPerezAdsuar** [comment]
Hi,

I've already solved. The problem was that from iOS 10 is required to specify the application in the PLIST config. In previous versions it was not required.

Thank you

**Comment by EddyVerbruggen** [comment]
Hi, are you opening the app from a browser? And that requires the app to whitelist itself in the plist? Please elaborate so I can update the code or readme.

Thanks!

**Comment by PabloPerezAdsuar** [comment]
Hi @EddyVerbruggen , 

I used the plugin called "cordova-plugin-customurlscheme". This plugin allows me to add records to PLIST file. Is it possible to add records to PLIST from your plugin?

Thanks!

**Comment by EddyVerbruggen** [comment]
Hi, that's the name of this plugin...

Can you please answer my previous question so I can decide what to do? If we need to whitelist the app in the plist then the plugin can take care of that.

**Comment by PabloPerezAdsuar** [comment]
Sorry, I was wrong to copy and paste. You have it rectified.
