### ISSUE TITLE
Redirect to Playstore App link if App is not installed

### ISSUE THREAD

**Issue by ozmursleen** [EddyVerbruggen/Custom-URL-scheme#207]
Hey Eddy,

How can i implement if app is not installed redirect it to playstore app page. If app is installed its working fine.

Please help.

**Comment by ozmursleen** [comment]
No worries sorted it out. Thanks for the plugin.

**Comment by coolara** [comment]
> No worries sorted it out. Thanks for the plugin.

hi  what's ur solution ?
