### ISSUE TITLE
Parameters how to receive it

### ISSUE THREAD

**Issue by giantss** [EddyVerbruggen/Custom-URL-scheme#208]
If I need to open the corresponding page in the cordova app,Parameters how to receive it？

**Comment by leandroguimaraes** [comment]
"Handling Custom URLs" from here https://medium.com/angularjs-articles/deep-linking-in-ionic-mobile-applications-44d8b4685bb3#.p1ap2r6oo does the trick

**Comment by leandroguimaraes** [comment]
I forgot to say that this is a Ionic / AngularJS solution

**Comment by giantss** [comment]
thanks,I'm used that sencha touch + cordova

**Comment by giantss** [comment]
I was too careless,this plugin can be used.
