### ISSUE TITLE
Cold start does not work on IOS

### ISSUE THREAD

**Issue by srameshr** [EddyVerbruggen/Custom-URL-scheme#209]
```
index.html


<body>
  <script>
      function handleOpenURL(url) {
        alert(url)
        setTimeout(function() {
          window.localStorage.setItem("externalLoad", JSON.stringify(url));
        }, 0);
      }
    </script>
</body>


app.js

$ionicPlatform.ready(() => {
  function navigateEv() {
    alert("From cold start")
  }
  $timeout(() => {
     navigateEv();
   }, 750);
})
  
```

The problem is ```handleOpenURL``` does not fire from cold start.

```
IOS Version: 10.0
Cordova version: 6.3.1
IOS Cordova: 4.2.1
```

**Comment by leandroguimaraes** [comment]
Try "Handling Custom URLs" from here https://medium.com/angularjs-articles/deep-linking-in-ionic-mobile-applications-44d8b4685bb3#.p1ap2r6oo

**Comment by srameshr** [comment]
Solved it. It was CSP issue.

**Comment by henkkelder** [comment]
Could you please describe your solution?

**Comment by srameshr** [comment]
I removed the CSP (the whole meta tag) and enabled key chain access as I was developing on IOS 10 via xcode. 

If you dont know how to enable keychain access, please google it
