### ISSUE TITLE
Android App opening inside Chrome after clicking the customscheme://

### ISSUE THREAD

**Issue by alexlopezit** [EddyVerbruggen/Custom-URL-scheme#24]
I've got my app opening from a link perfect on iOS, on Android when I click the custom link ("sample://”) it launches my app, however, if I look at the task switcher, my app isn't listed. Instead, Chrome is shown, with my app's screen shot.

![screenshot_2014-06-17-08-57-29](https://cloud.githubusercontent.com/assets/1654135/3294470/f476246e-f5a9-11e3-8969-e10d0502b7f8.png)

Update:

Cordova 3.1
Nexus 4/Android 4.4
Nexus 7/Android 4.4.3

**Comment by quicklyfrozen** [comment]
Seems like you need to add an "AndroidLaunchMode" preference to config.xml instead.  A change to android:launch in the android manifest will get overwritten by a cordova build, at least in cordova 5.1.1.
