### ISSUE TITLE
Can you publish the latest version on npm ?

### ISSUE THREAD

**Issue by cadesalaberry** [EddyVerbruggen/Custom-URL-scheme#243]
Hi there,

Could you release the new version on npm ?

This [commit](https://github.com/EddyVerbruggen/Custom-URL-scheme/commit/9efdafb9bb22db250a229853005a065c942a96f7) is currently blocking the build on windows.

I have replaced the `spec` with the following to have it work on my platform in case anybody needs a quickfix:
```xml
<plugin name="cordova-plugin-customurlscheme" spec="https://github.com/cadesalaberry/Custom-URL-scheme.git">
    ...
</plugin>
```

or:
```
cordova plugin add https://github.com/cadesalaberry/Custom-URL-scheme --save
```

**Comment by EddyVerbruggen** [comment]
Done (4.3.0).
