### ISSUE TITLE
Can't install with Meteor

### ISSUE THREAD

**Issue by erperejildo** [EddyVerbruggen/Custom-URL-scheme#246]
I'm using Meteor 1.4.2.6 and to install Cordova plugins I need to run this command `meteor add cordova:plugin-name@version`.

I can install with that this one but not with `--variable URL_SCHEME=mycoolapp`. With this I get this error:

> --variable: unknown option.
> Usage: meteor add <package> [package..]

**Comment by layik** [comment]
$ meteor add cordova:cordova-plugin-customurlscheme:@4.3.0
supposedly adds it to the meteor project but fails on build.

**Comment by andruli** [comment]
@erperejildo @layik you need to pass the configuration option in the `mobile-config.js` file:
```
App.configurePlugin('cordova-plugin-customurlscheme', {
  URL_SCHEME: 'mycoolapp',
});
```

**Comment by erperejildo** [comment]
Perfect, didn't know that way. 
@EddyVerbruggen can you add maybe this to the README for Meteor users?

**Comment by EddyVerbruggen** [comment]
@erperejildo I'd happily merge a PR.
