### ISSUE TITLE
handleOpenURL doesn't fire on IOS

### ISSUE THREAD

**Issue by jonathanhollander** [EddyVerbruggen/Custom-URL-scheme#251]
I've installed the plugin, and although when I access my custom URL I do get redirected to the app, the "handleOpenURL" function is never called.

I'm testing on iOS with iPhone6+
Cordova 7.0.1
cordova ios: 4.4.0
iOS: 10.3.2

Something I don't understand is on your directions you show taht when you add the plugin with --save it adds this to the config:

<feature name="Custom URL scheme">
    <param name="id" value="cordova-plugin-customurlscheme" />
    <param name="url" value="https://github.com/EddyVerbruggen/Custom-URL-scheme.git" />
    <variable name="URL_SCHEME" value="mycoolapp" />
  </feature>

But no where in my config.xml do I see any of this. Do I need to manually add it? Again the plugin is working so i know i installed it correctly just the "handleOpenURL" is never called. Is this <feature> xml bit required for the handleOpenURL to work?

**Comment by jonathanhollander** [comment]
sorry I had my function in the wrong place, it works correctly

**Comment by william-beange-hs** [comment]
@jonathanhollander where is the right place?
