### ISSUE TITLE
Not opening the app from email client!

### ISSUE THREAD

**Issue by scarinciotto** [EddyVerbruggen/Custom-URL-scheme#259]
Hi to All,

in the regular html website page from browser the link myapp:// works fine, but if I send the same html page to the email client, from there the "custom link" doesn't work.

Maybe the workaround is to redirect the html page from email client to the website, and then from there open my app by "custom link" (e.g. domready).... but it's no the best thing in my opinion.

Do you have any idea?
thanks

**Comment by EddyVerbruggen** [comment]
Yep that’s the best approach because you get to write fallback code etc.
