### ISSUE TITLE
<gap:plugin /> malformed XML

### ISSUE THREAD

**Issue by thesequelgroup** [EddyVerbruggen/Custom-URL-scheme#260]
I get a malformed XML error when deploying the app with the directions in the readme file. It's my understanding that the <gap:plugin /> syntax was removed quite some time ago, so the readme should be updated accordingly as to not confuse other devs. This is what worked for me:

`
<plugin name="cordova-plugin-customurlscheme" source="npm">
        <param name="URL_SCHEME" value="coolapp" />
    </plugin>
`

**Comment by EddyVerbruggen** [comment]
Thanks, I'd love to merge a PR that fixes it.
