### ISSUE TITLE
Unable to build android project after installing Custom-URL-scheme

### ISSUE THREAD

**Issue by anandkshitiz** [EddyVerbruggen/Custom-URL-scheme#284]
I am getting below error and the project is not getting built after i installed this plugin.

>Discovered plugin "LaunchMyApp" in config.xml. Adding it to the project

>Failed to restore plugin "LaunchMyApp" from config.xml. You might need to try adding it again. Error: >Error: npm: Command failed with exit code 1 Error output:
>npm ERR! code E404
>npm ERR! 404 Not found : LaunchMyApp
>npm ERR! 404
>npm ERR! 404  'LaunchMyApp' is not in the npm registry.
>npm ERR! 404 Your package name is not valid, because
>npm ERR! 404  1. name can no longer contain capital letters
>npm ERR! 404
>npm ERR! 404 Note that you can also install from a
>npm ERR! 404 tarball, folder, http url, or git url.

>npm ERR! A complete log of this run can be found in:

**Kindly help**

**Comment by anandkshitiz** [comment]
Fixed after removing the "LaunchMyApp" configuration from package.json

**Comment by dadamschi** [comment]
@anandkshitiz I am having the same issue and have read numerous posts talking about removing the LaunchMyApp config from the package.json. 

Full disclosure, I am using corber on top of Cordova so there may be something different but when I remove the LaunchMyApp from the package.json and then start the app, LaunchMyApp is automatically added back in to the package.json and returns the same error.  
  
Any suggestions?

**Comment by juniCodefire** [comment]
please why is this issue closed , i have not seen any possible solution

**Comment by juniCodefire** [comment]
after removing the LauchMyApp it automatically returns to my package,json file

**Comment by juniCodefire** [comment]
i just solve this ...i remove the plugin with name LauchMyApp from the config.xml and replaced it with this

**Comment by juniCodefire** [comment]
<plugin name="cordova-plugin-customurlscheme"
        spec="git+https://github.com/EddyVerbruggen/Custom-URL-scheme.git"> 
        <variable name="URL_SCHEME" value="Url Scheme" /> 
        <variable name="ANDROID_SCHEME" value=" " /> 
        <variable name="ANDROID_HOST" value=" " /> 
        <variable name="ANDROID_PATHPREFIX" value="/" /> 
     </plugin>

**Comment by juniCodefire** [comment]
<plugin name="cordova-plugin-customurlscheme"
        spec="git+https://github.com/EddyVerbruggen/Custom-URL-scheme.git"> 
        <variable name="URL_SCHEME" value="developnd" /> 
        <variable `name="ANDROID_SCHEME"` value=" " /> 
        <variable name="ANDROID_HOST" value=" " /> 
        <variable name="ANDROID_PATHPREFIX" value="/" /> 
     </plugin>

**Comment by juniCodefire** [comment]
`  <plugin name="cordova-plugin-customurlscheme"
        spec="git+https://github.com/EddyVerbruggen/Custom-URL-scheme.git"> 
        <variable name="URL_SCHEME" value="developnd" /> 
        <variable name="ANDROID_SCHEME" value=" " /> 
        <variable name="ANDROID_HOST" value=" " /> 
        <variable name="ANDROID_PATHPREFIX" value="/" /> 
     </plugin>`

**Comment by juniCodefire** [comment]
`  <plugin name="cordova-plugin-customurlscheme"
        spec="git+https://github.com/EddyVerbruggen/Custom-URL-scheme.git"> 
        <variable name="URL_SCHEME" value="your url scheme" /> 
        <variable name="ANDROID_SCHEME" value=" " /> 
        <variable name="ANDROID_HOST" value=" " /> 
        <variable name="ANDROID_PATHPREFIX" value="/" /> 
     </plugin>`
