### ISSUE TITLE
Cordova 9 CLI broke plugin for Windows platform

### ISSUE THREAD

**Issue by marcuspridham** [EddyVerbruggen/Custom-URL-scheme#292]
In Cordova 9, there is change: Deprecate `requireCordovaModule` for non-Cordova modules.
https://github.com/apache/cordova-lib/pull/707

This is breaking the current published version of the plugin on NPM when using Windows.  You get the following error: 
```
Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
```

The problem hook is:
```
 <hook type="before_prepare" src="src/windows/hooks/prepare-manifest.js" />
```

It looks like the hook is using requireCordovaModule but it has been removed since the last publish of the plugin:
https://github.com/EddyVerbruggen/Custom-URL-scheme/commit/9f1cc218d0a535269082d249d1a8406da0ff13c9
 
Can a new version be published with this change?  Thanks!

**Comment by EddyVerbruggen** [comment]
Sure, however, AFAIK that change has not been tested. Can you confirm it doesn't break anything?

**Comment by peterkissdeveloper** [comment]
Hi Eddy,

Thank you for responding so quick.
I have checked the modification on Windows and small modifications. I tried to create a new branch on your repo but I don't have permission.
The newly added tags has to be in the uap namespace and the package.windows80.appxmanifest file doesn't exist anymore but the package.windows10.appxmanifest exists so I changed this property.

Please add this to your current commit and then it will work fine.

Thanks,
Peter

  <platform name="windows">
    <config-file target="package.windows.appxmanifest" parent="/Package/Applications/Application/Extensions">
      <uap:Extension Category="windows.protocol" StartPage="www/index.html">
        <uap:Protocol Name="$URL_SCHEME" />
      </uap:Extension>
    </config-file>
    <config-file target="package.windows10.appxmanifest" parent="/Package/Applications/Application/Extensions">
      <uap:Extension Category="windows.protocol" StartPage="www/index.html">
        <uap:Protocol Name="$URL_SCHEME" />
      </uap:Extension>
    </config-file>
    <config-file target="package.phone.appxmanifest" parent="/Package/Applications/Application/Extensions">
      <uap:Extension Category="windows.protocol" StartPage="www/index.html">
        <uap:Protocol Name="$URL_SCHEME" />
      </uap:Extension>
    </config-file>
    <js-module src="www/windows/LaunchMyApp.js" name="LaunchMyApp">
      <clobbers target="window.plugins.launchmyapp" />
    </js-module>
  </platform>

**Comment by peterkissdeveloper** [comment]
<platform name="windows">
    <config-file target="package.windows.appxmanifest" parent="/Package/Applications/Application/Extensions">
      <uap:Extension Category="windows.protocol" StartPage="www/index.html">
        <uap:Protocol Name="$URL_SCHEME" />
      </uap:Extension>
    </config-file>
    <config-file target="package.windows10.appxmanifest" parent="/Package/Applications/Application/Extensions">
      <uap:Extension Category="windows.protocol" StartPage="www/index.html">
        <uap:Protocol Name="$URL_SCHEME" />
      </uap:Extension>
    </config-file>
    <config-file target="package.phone.appxmanifest" parent="/Package/Applications/Application/Extensions">
      <uap:Extension Category="windows.protocol" StartPage="www/index.html">
        <uap:Protocol Name="$URL_SCHEME" />
      </uap:Extension>
    </config-file>
    <js-module src="www/windows/LaunchMyApp.js" name="LaunchMyApp">
      <clobbers target="window.plugins.launchmyapp" />
    </js-module>
  </platform>

**Comment by peterkissdeveloper** [comment]
`  <platform name="windows">
    <config-file target="package.windows.appxmanifest" parent="/Package/Applications/Application/Extensions">
      <uap:Extension Category="windows.protocol" StartPage="www/index.html">
        <uap:Protocol Name="$URL_SCHEME" />
      </uap:Extension>
    </config-file>
    <config-file target="package.windows10.appxmanifest" parent="/Package/Applications/Application/Extensions">
      <uap:Extension Category="windows.protocol" StartPage="www/index.html">
        <uap:Protocol Name="$URL_SCHEME" />
      </uap:Extension>
    </config-file>
    <config-file target="package.phone.appxmanifest" parent="/Package/Applications/Application/Extensions">
      <uap:Extension Category="windows.protocol" StartPage="www/index.html">
        <uap:Protocol Name="$URL_SCHEME" />
      </uap:Extension>
    </config-file>
    <js-module src="www/windows/LaunchMyApp.js" name="LaunchMyApp">
      <clobbers target="window.plugins.launchmyapp" />
    </js-module>
  </platform>
`

**Comment by EddyVerbruggen** [comment]
Hi! Yeah, permissions are fortunately not granted by default on Git repos 😊

The way to go about this is forking this repo, then adding the code to your fork, and creating a pull request. It's a good skill to learn and possibly easier than you might think.

**Comment by peterkissdeveloper** [comment]
I have created the pull request as you wrote.

**Comment by EddyVerbruggen** [comment]
Thanks a lot, @peterkissdeveloper! I'm not a Windows user, so if y'all think this is good to go, I'll push it to npm in an hour.

**Comment by peterkissdeveloper** [comment]
I am working on the Windows side of our hybrid SDK and I can confirm that this is working fine.
Thank you for pushing it to the npm!

**Comment by EddyVerbruggen** [comment]
It's on npm now. Thanks all!

**Comment by krishtel** [comment]
Hi, what was the fix for this?  I keep running into this error when trying to build.  This is on Windows Git Bash:

```
Using "requireCordovaModule" to load non-cordova module "elementtree" is not su pported. Instead, add this module to your dependencies and use regular "require " to load it.
```

**Comment by rahulbpatel** [comment]
Hi, what was the fix for this? I keep running into this error when trying to build. This is on Windows Git Bash:
```
Using "requireCordovaModule" to load non-cordova module "elementtree" is not su pported. Instead, add this module to your dependencies and use regular "require " to load it.
```

**Comment by peterkissdeveloper** [comment]
The issue which you are receiving is caused by the Cordova version 9. This deprecated the requireCordovaModule.
Originally this plugin used it in a hook:
<hook type="before_prepare" src="src/windows/hooks/prepare-manifest.js" />
This was removed. Please check the plugin.xml in your version and it shouldn't contain the previous line.

**Comment by rahulbpatel** [comment]
Right, that's what I'm trying to understand.  I am installing v4.4.0.  Based on this issue's history, looks like it was fixed with that version but I am still getting that error because `prepare-manifest.js` has `requireCordovaModule` calls.

**Comment by peterkissdeveloper** [comment]
The prepare-manifest.js file is not called in the plugin.xml in case of 4.4.0:
https://github.com/EddyVerbruggen/Custom-URL-scheme/blob/4.4.0/plugin.xml

In case of 4.3.0 there it is:
https://github.com/EddyVerbruggen/Custom-URL-scheme/blob/4.3.0/plugin.xml

I don't know what could be the issue on your side but in 4.4.0 the js file should not be called on Windows.
