### ISSUE TITLE
HandleOpenUrl not called on warm launch (Cordova platform IOS 5.0.0)

### ISSUE THREAD

**Issue by Vito96** [EddyVerbruggen/Custom-URL-scheme#295]
Hi,
I have updated on my app the cordova platform of IOS to the version 5.0.0, from here the handleOpenUrl does not called on warm start launches.
Can be a problem similar to the problem of cordova ios 3.8.0?

(handleOpenUrl is called only on first launch from xcode)

Thanks.

**Comment by gambarle** [comment]
I'm experiencing an issue that might be related. 
using Ionic 3, cordova-ios 5.0.0, launching my app from within another app (TestFlight), handleOpenUrl is not called.
It has been working up until and including cordova-ios 4.5.5

**Comment by rabeeScryptech** [comment]
I am experiencing the same problem , have anyone managed to solve it ?

**Comment by gambarle** [comment]
I'm using the [Deeplinks](https://github.com/ionic-team/ionic-plugin-deeplinks) plugin instead.
So far i have not had problems

**Comment by SergTomcat** [comment]
rabeeScryptech, I managed to solve it, but in my case this plugin was interfering with other one (azure services)

**Comment by haveamission** [comment]
@gambarle - can you give an example of how you're using deeplinks? I am trying to use it with a non-ionic setup and having no luck

**Comment by gczudowski** [comment]
Hi! 
I have the same issue after updating <preference name="phonegap-version" value="cli-9.0.0"/> from 8.0.0 (uses cordova 5.0).

window.handleOpenURL is not called at all

Did anyone manage to solve the issue somehow?

**Comment by super-maoMao** [comment]
I am experiencing the same problem , How to deal with it ?

**Comment by guanyuan** [comment]
> interfering

Hi, there.  I have this issue too.
So how did you solve it?
Can you share your solution?

**Comment by guanyuan** [comment]
> rabeeScryptech, I managed to solve it, but in my case this plugin was interfering with other one (azure services)

Hi, there. I have this issue too.
So how did you solve it?
Can you share your solution?
