### ISSUE TITLE
Is this plugin alive?

### ISSUE THREAD

**Issue by codeability-ab** [EddyVerbruggen/Custom-URL-scheme#297]
Hello!
Does this plugin work as it's supposed to or is it dead?

I'm reading the long list of issues and it seems like there are a lot of problems with issues dating back to 2014.

Are there any good alternatives out there?

I only need it for the iOS-version of my app to enable the Swedish BankID app to redirect back to my app after a successful login.

best regards Johan

PS: BankID? "BankID is an electronic identification solution that allows companies, banks, organizations and governments agencies to authenticate and conclude agreements with individuals over the Internet" from www.bankid.com/en

**Comment by EddyVerbruggen** [comment]
Have your tried it before asking?

**Comment by codeability-ab** [comment]
Yes a quick attempt, but I had problems making it work and I got a bit worried when I saw the amount of issues that are still open.

I work for a bank and all open source code we're using is being reviewed regarding for example no of open issues, no of contributors, no of recent checkins etc before being accepted as part of our solutions.

best regards Johan

PS: I'm not a big contributor to open source myself but people in my team are so we're not just lazy open source consumers :-)

**Comment by EddyVerbruggen** [comment]
I understand. Not sure it still works to be honest, but I have no reason to assume it doesn’t.

Perhaps it’s best to look at the iOS source in this repo. There’s not much code involved for iOS at all so since that’s the only platform you need it may be easier to not use a plugin at all. Or a stripped fork.

**Comment by codeability-ab** [comment]
Thanks for your tips :-)
/johan

**Comment by codeability-ab** [comment]
FYI: it works perfectly! Don't know why it didn't work in my first attempt.
