### ISSUE TITLE
cordova platform ios 5.0.0 function handleOpenURL(url) doesn't work

### ISSUE THREAD

**Issue by gasci** [EddyVerbruggen/Custom-URL-scheme#300]
After the latest update, function handleOpenURL(url) doesnt't work on ios. 

Xcode error:
2019-06-28 19:09:39.537173+0300 Curiosmo[23025:1580321] FB handle url: curiosmo://question/396
2019-06-28 19:09:39.727818+0300 Curiosmo[23025:1580518] <FIRAnalytics/WARNING> Implementation of application:openURL:sourceApplication:annotation: not found. Please add the handler into your App Delegate. Class: AppDelegate

**Comment by tehdb** [comment]
had a similar issue, just updated to `cordova-ios@5.0.1` and the problem seems to be gone

**Comment by thomas-alrek** [comment]
@gasci @tehdb I am still having this issue on `cordova-ios@5.0.1` and the latest version of this plugin. My custom URL scheme causes the app to open, but the handleOpenURL function is never called.

Where you able to solve this?

**Comment by TimBosbec** [comment]
Also I have the same problem with cordova-ios@5.0.1 . It works good when the app is running in the background but on coldstart the handleOpenUrl is not called. Works flawless on Android though

**Comment by ludufre** [comment]
+1

**Comment by gasci** [comment]
Unfortunately, I still have no solutions other than using cordova-ios@4.5.5

**Comment by ludufre** [comment]
In Ionic 4 I managed to make it work with ionic-plugin-deeplinks and a workaround. 

If you use Ionic I can explain what I did

**Comment by TimBosbec** [comment]
> In Ionic 4 I managed to make it work with ionic-plugin-deeplinks and a workaround.
> 
> If you use Ionic I can explain what I did

I actually solved it this way too. As ionics deeplinks plugin has support for deeplinking and custom schemes.

**Comment by gasci** [comment]
Have you found a solution?

**Comment by abhishekdana1999** [comment]
> Have you found a solution? Unfortunately, I develop pure cordova apps without ionic.

Same issue here
