### ISSUE TITLE
No Copyright and License File

### ISSUE THREAD

**Issue by modimoni** [EddyVerbruggen/Custom-URL-scheme#309]
I am unable to find a LICENSE file in Git nor copyright information in the header section of source files. Please add either or both of them.

Thanks
Modi

**Comment by EddyVerbruggen** [comment]
This will have to do: https://github.com/EddyVerbruggen/Custom-URL-scheme/blob/c1a0de2ad3a03efc01f4656e33391c922279e8f3/package.json#L38
