### ISSUE TITLE
Steps during installation process and using it

### ISSUE THREAD

**Issue by somixyz** [EddyVerbruggen/Custom-URL-scheme#310]
Hello,

I've been following complete step by step everything you write in README file, I got that plugin in project and folder structure [http://prntscr.com/qc3c3l](url) with LaunchMyApp.java and LaunchMyApp.js files, but cant cache you what to do next.
I used PhoneGap to install this plugin automatically via CLI, so according to your explanation in README file, I should skip everything with Manually installations, and I did it. Didn't touch my config file.
But what should I do next? How and where I should specify my URLs paths for accessing my application through links?

Thanks

**Comment by dadamschi** [comment]
Same issue. The install seems to do the bare CLI minimum and not touch any files other than package.json.
