### ISSUE TITLE
handleOpenURL not working in IOS 12

### ISSUE THREAD

**Issue by douglasendrew** [EddyVerbruggen/Custom-URL-scheme#345]
Hello guys, i have a problem on execute the function handleOpenURL on IOS 12 (i try on IOS 16 and running).

My code:

`window.handleOpenURL = function(url) {
        setTimeout(function(){
            var link = url.split("?");
            var keysPair = link[1].split("&");
            var event_key = keysPair[0].split("=");
            if(event_key[0] == "event")
            {
                alert("Entrando no evento...");
                loadPage(true, "request-entry-event", { id: event_key[1] }, true);
            }
        },0);
    };`

Where is the error?

**Comment by douglasendrew** [comment]
ok!

**Comment by raeesaa** [comment]
@douglasendrew were you able to get this to working? I am facing this issue with all iOS versions.
