### ISSUE TITLE
handleOpenURL is not getting called on Android

### ISSUE THREAD

**Issue by JonathanAquino** [EddyVerbruggen/Custom-URL-scheme#51]
Here is a simple test case that shows that handleOpenURL is not getting called on Android.
1. Create a Cordova app and add the LaunchMyApp plugin:
   
   ```
   cordova create abc
   cd abc
   cordova platform add android
   cordova plugin add https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git --variable URL_SCHEME=mycoolapp
   ```
2. Edit www/index.html to be the following:
   
   ```
   <!DOCTYPE html>
   <html>
   <head>
       <title></title>
       <script>
           handleOpenURL = function (url) {
               setTimeout(function(){
                   window.foo = 'The url is ' + url;
               },0);
           };
       </script>
   </head>
   <body>
       <a href="#" onclick="alert(window.foo);">Alert the value of "foo"</a>
   </body>
   </html>
   ```
3. Run the app.
   
   ```
   cordova run android
   ```
4. Go to the browser and visit [this page](jonathanaquino.com/aaa.html).
5. Click the link in that page. You will be taken to the app.
6. Click "Alert the value of "foo"".

// Expected: The alert dialog shows "The url is mycoolapp://index.html?foo=bar".
// Actual: The alert dialog shows "undefined".

This does work on iOS, just not Android.

**Comment by bennycheung** [comment]
Jonathan, I have the same problem. Can you tell me which 'cordova.js' to get and where to put it.
Thanks in advance
