### ISSUE TITLE
Get error when installing for iOS

### ISSUE THREAD

**Issue by eddanger** [EddyVerbruggen/Custom-URL-scheme#57]
Works for android but I get this issue when installing for iOS via: `cordova plugin add https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git --variable URL_SCHEME=mycoolapp`
```
Installing "nl.x-services.plugins.launchmyapp" for ios
Failed to install 'nl.x-services.plugins.launchmyapp':undefined
undefined
```

**Comment by EddyVerbruggen** [comment]
Can you try updating your git client and run the command again? The usefulness of this reply depends on the platform you're building this on (Windows or Mac).
