### ISSUE TITLE
window.open(url, '_blank') does not trigger handleOpenURL() on Android. Fine on iOS.

### ISSUE THREAD

**Issue by ldeavila** [EddyVerbruggen/Custom-URL-scheme#61]
I'm not sure if this is an issue with the Custom-URL-scheme plugin or InAppBrowser plugin. 

Basically, `handleOpenURL()` is not invoked when the browser get a custom url scheme , i.e. `mycoolapp://`, from the server if I use `window.open(url, '_blank')`. If I use `window.open(url, '_system')`, then `handleOpenURL()` is indeed invoked.

Works fine on iOS. I'm running Android 5.0.1 

Thoughts? Any guidance would be appreciated.

**Comment by EddyVerbruggen** [comment]
It's an Android 5 Chrome issue. You'll need to use `document.location=url` for custom url schemes to work.
