### ISSUE TITLE
Does not call the handleOpenUrl function when app is not opened in the background and the custom url scheme is called to open the app

### ISSUE THREAD

**Issue by ilyakar** [EddyVerbruggen/Custom-URL-scheme#64]

**Comment by EddyVerbruggen** [comment]
Cordova-iOS 3.7.0 perhaps? Try 3.6.3 as that version has a major bug.

**Comment by ilyakar** [comment]
I’m using cordova version 4.1.2

**Comment by EddyVerbruggen** [comment]
That's the CLI version, not Cordova-iOS. Anyway, try `cordova platform add ios@3.6.3` and test again.

**Comment by ilyakar** [comment]
Yes it worked! Thank you! Is this written somewhere in the docs?

**Comment by EddyVerbruggen** [comment]
No it should :+1: 
There are some similar issues in the repo though.

The thing is, I hoped it would be fixed quickly, but it seems scheduled for 3.8.0 at the moment. [See this issue for details](https://issues.apache.org/jira/browse/CB-7606).

I think I'll add a big fat note to the readme now ;)

**Comment by ilyakar** [comment]
I think that’d help people in the future yes, I was having difficulties with this for over a month. I’m just happy it’s solved, thanks again! :)

**Comment by EddyVerbruggen** [comment]
Great, [hope this helps](https://github.com/EddyVerbruggen/Custom-URL-scheme/blob/master/README.md#beware-this-apache-cordova-issue-causes-problems-with-cordova-ios-370-the-handleopenurl-function-is-not-invoked-upon-cold-start-use-cordova-ios-363-or-lower-for-the-moment-cordova-platform-add-ios363).

**Comment by leonprou** [comment]
I'm using iOS  3.7.0, and the plugin seems to work
guess the issue is fixed

**Comment by EddyVerbruggen** [comment]
Cordova-ios 3.8.0 has just been released, including [the fix for CB-7606](https://issues.apache.org/jira/browse/CB-7606). This should fix your trouble, thanks for the patience.
