### ISSUE TITLE
Compatibility with WebIntent plugin

### ISSUE THREAD

**Issue by dpaloucva** [EddyVerbruggen/Custom-URL-scheme#65]
Hi,

I'm trying to use the [Android WebIntent] (https://github.com/florentvaldelievre/virtualartifacts-webintent/) plugin to be able to open files with my app. If I add your plugin to the project, the WebIntent plugin stops working, I can't get the file URL anymore. I've been looking at your code and this is the line that's causing me trouble:

> intent.setData(null);

It's the one used in the `execute` function. 

With the WebIntent plugin, the app receives an Intent with a string extra: the URL of the file to open with the app. Something like:

> file:///storage/sdcard0/Download/20141218.pdf

Since your plugin is setting this Intent data to null, the WebIntent plugin can't get it anymore. 

Can you please add more checks to your code to prevent setting the data to null unless it's absolutely necessary?

Thank you! :)

**Comment by symbiat** [comment]
@dpaloucva Any luck with this? Im trying to use this plugin alongside the WebIntent plugin and my `handleOpenURL()` method never fires.

**Comment by EddyVerbruggen** [comment]
Kinda missed this issue - will look into it!

**Comment by EddyVerbruggen** [comment]
Hi @symbiat, @dpaloucva (sorry it took so long), can you try the plugin from the master repo? It has a potential fix but as I'm not sure how you're using the WebIntent plugin I'm not sure it fixes your issue.

**Comment by symbiat** [comment]
@EddyVerbruggen Im using the WebIntent plugin purely to capture the standard Android sharing intent. Im specifying MIME types for text (e.g. URLs) and images (which the app uploads). My config looks like this:
```
            <intent-filter android:label="@string/launcher_name">               
                <action android:name="android.intent.action.MAIN" />            
                <category android:name="android.intent.category.LAUNCHER" />    
            </intent-filter>                                                    
            <intent-filter>                                                     
                <action android:name="android.intent.action.SEND" />            
                <category android:name="android.intent.category.DEFAULT" />     
                <data android:mimeType="text/plain" />                          
            </intent-filter>                                                    
            <intent-filter>                                                     
                <action android:name="android.intent.action.SEND" />            
                <category android:name="android.intent.category.DEFAULT" />     
                <data android:mimeType="image/*" />                             
            </intent-filter>                                                    
            <intent-filter>                                                     
                <data android:scheme="ussie" />                                 
                <action android:name="android.intent.action.VIEW" />            
                <category android:name="android.intent.category.DEFAULT" />     
                <category android:name="android.intent.category.BROWSABLE" />   
            </intent-filter>         
```
So from top to bottom we have: standard launcher intent, sharing text intent, sharing image intent, then our custom scheme intent.

**Comment by dpaloucva** [comment]
Hello Eddy,

I don't have time to perform a deep testing now, I did a quick test and it didn't work either. I looked at your commit and I see you're adding more checks in the `onNewIntent` function, but the one that was causing me problems was the setData(null) in the `execute` function. I hope that gives you some clue on how to fix this. I'll try to perform more tests as soon as I can.

Thanks!

**Comment by EddyVerbruggen** [comment]
It does help, let me amend the fix first, thx

**Comment by EddyVerbruggen** [comment]
Hi @dpaloucva the latest commit should *really* fix it.

Let me know if it works OK for you.
