### ISSUE TITLE
Cordova iOS 3.8.0

### ISSUE THREAD

**Issue by Hirbod** [EddyVerbruggen/Custom-URL-scheme#67]
Hi @EddyVerbruggen,

can you confirm that the bugs with 3.7.1 are now fixed in 3.8.0?

Thank you very much!

**Comment by EddyVerbruggen** [comment]
They should be, as the fix is part of the latest release. Please update your cordova tools and give it a spin.

**Comment by Hirbod** [comment]
Confirmed! Works well on Cordova iOS 3.8.0

**Comment by EddyVerbruggen** [comment]
Ha, very pleased to hear that! Thanks for confirming.
