### ISSUE TITLE
Gmail is not showing custom scheme links

### ISSUE THREAD

**Issue by sebrojas14** [EddyVerbruggen/Custom-URL-scheme#70]
Hello, I looked this plugin with a lot of interest, principally I think to use it for a password recovery functionality of an app. But I have a problem, I tried to send the link in a mail, but gmail clients are not showing the link (only the titles, is not clicleable) so basically it doesn't work. I could only test it from a link in a website. Any clue?

**Comment by EddyVerbruggen** [comment]
I don't think this plugin can influence the way GMail renders links, so you'd have to link to a web page which in turn links to your app.

**Comment by sebrojas14** [comment]
You are right, but maybe you can change your documentation? because the documentation refers to email the link with the custom scheme
