### ISSUE TITLE
Problem with window.open and custom url schemes in iOS?

### ISSUE THREAD

**Issue by lars21st** [EddyVerbruggen/Custom-URL-scheme#71]
Hi

I've got the plugin setup with Phonegap build using the instructions provided, IE i added this to my config.xml:

<.gap:plugin name="nl.x-services.plugins.launchmyapp">
<.param name="URL_SCHEME" value="centcq" />
<./gap:plugin>

This works great on Android but on iOS nothing happens when I click the same link that works on android. Is there any additional step I have to take to make it work on iOS?

**Comment by EddyVerbruggen** [comment]
Let me get this clear.. did you load a webpage in the Safari browser? Does that webpage contain a link to your app and your app didn't load after clicking it?

**Comment by lars21st** [comment]
Hi

Thanks for the quick response!

Yes, that is what I did, sorry for being unclear. I'm using a centcq:// address in the link.

To be extra specific, this is how the link is being created (as a button):

$('#appLoginButton').bind('click', function() {
					window.open('centcq://mobileKey=' + mobileKey);
				});

**Comment by EddyVerbruggen** [comment]
To be sure, - that button, is it part of a public website or part of an app?

If it's a webpage, can you try a regular `<a href="centcq://">open</a>` link?

**Comment by lars21st** [comment]
Thank you!

That did the trick. Apparently there is something about window.open that doesn't want to run on iOS, at least not with custom url schemes.

Just to answer your question for anyone interested: the button is on a public website, not in an app.

**Comment by EddyVerbruggen** [comment]
Re: window.open - it may be because it's a popup which Safari blocks by default.
