### ISSUE TITLE
updating platform in cordova causes error

### ISSUE THREAD

**Issue by mluria** [EddyVerbruggen/Custom-URL-scheme#73]
If I have the plugin added and then add another platform, I get the error below:

cordova platform add browser
...
Installing "nl.x-services.plugins.launchmyapp" for browser
Failed to install 'nl.x-services.plugins.launchmyapp':Error: Variable(s) missing: URL_SCHEME
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:299:23
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
   

My workaround is to do:

cordova plugin rm nl.x-services.plugins.launchmyapp
cordova platform add browser
cordova plugin add https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git --variable URL_SCHEME=myscheme

It works but it is a pain.

Is there a solution to this?

m

and then

**Comment by EddyVerbruggen** [comment]
Perhaps it can be solved by moving [this line](https://github.com/EddyVerbruggen/Custom-URL-scheme/blob/master/plugin.xml#L24) inside the iOS and Android platform blocks. Is that something you're willing to test?

**Comment by mluria** [comment]
sure, I don't reallly understand what you want me to try, the code: 
<preference name="URL_SCHEME" />

is already in plugin.xml in www

**Comment by andruhon** [comment]
I've tried to add <preference name="URL_SCHEME" value="myapp" /> into <platform name="android"> and after other global perferences:

<content src="index.html" />
<access origin="*" />
<preference name="URL_SCHEME" value="myapp" />

and still getting the message about missing variable

**Comment by andruhon** [comment]
Created a new issue #76 with resolution of this problem
