### ISSUE TITLE
Android - App hasn't call with URLSheme

### ISSUE THREAD

**Issue by Frulko** [EddyVerbruggen/Custom-URL-scheme#74]
Hi, 
I use cordova 4.3.0 and my app on iOS work fine with your plugin but on Android it doesn't work. I tried to make an HelloWorld Android app for see and it work but my phonegap/cordova app seem to not handle the url sheme. It's strange. Have you an idea? 
Thanks.

**Comment by EddyVerbruggen** [comment]
Hi, does `deviceready` fire on Android? If not, iOS will still work, but Android won't.

**Comment by c316** [comment]
+1 here.

What do you mean by deviceready? Are you saying your plugin doesn't work on Android?

**Comment by EddyVerbruggen** [comment]
With deviceready I mean if that isn't fired then that's the problem (perhaps you forgot to include a reference to cordova in your project).
