### ISSUE TITLE
Enabling 'back' to close activity

### ISSUE THREAD

**Issue by dpolivy** [EddyVerbruggen/Custom-URL-scheme#75]
This plugin seems to work really well, and allow deep linking to work the same as for my iOS app. One small thing I've come across is that the Android recommendations for launching apps with intents includes:

- Tapping the BACK button after opening a deep link leads you back to the previous screen.
https://developers.google.com/app-indexing/webmasters/checklist

It seems the best way to implement this is by calling `finish()` on the CordovaActivity; have you thought about exposing a JS API as part of this plugin that would allow that to be initiated from script? Or, is there an existing Cordova API that does the same thing?

I'd be happy to work up a PR if you think it'd be a useful addition.

**Comment by dpolivy** [comment]
After experimenting with this a bit more, I think I was able to find a workable solution that uses `navigator.app.clearHistory()` to clear out the back stack; thus, pressing the Android BACK button will essentially close the app and revert back to the previous activity.

**Comment by EddyVerbruggen** [comment]
Pretty smart fix. Feel free to open a PR to add this to the README.
