### ISSUE TITLE
"Error: Variable(s) missing: URL_SCHEME" when restoring plugins on platform add

### ISSUE THREAD

**Issue by andruhon** [EddyVerbruggen/Custom-URL-scheme#76]
cordova-cli 4.3.0
android-platform 3.7.1

When you do
>cordova plugin add https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git --variable URL_SCHEME=mycoolapp --save

It for some reason saves URL_SCHEME as &lt;param name="URL_SCHEME" value="slingshotapp" /&gt;
And later if you try to update or add a platform you'll get an error like this:

>Error: Variable(s) missing: URL_SCHEME

The URL_SCHEME variable should be saved as variable, not as param, here's an example:
```
    <feature name="Custom URL scheme">
        <param name="id" value="nl.x-services.plugins.launchmyapp" />
        <param name="url" value="https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git" />
        <variable name="URL_SCHEME" value="mycoolapp" />
    </feature>
```

I think it is something worth to document in README

**Comment by andruhon** [comment]
Created the MR #77 with updated README

**Comment by wallstudios** [comment]
I noticed the same issue today. As it had an error it was causing other issues with plugins. quick fix for me was to remove your plugin first then remove platform (I was doing a rebuild to get something working so needed to remove) and then re add platform. This loaded all of the other plugins correctly then I added back in yours with the --variable. worked fine that way.

**Comment by EddyVerbruggen** [comment]
@andruhon This sounds like a Plugman issue to me. I will add it to the readme, thanks for the PR!

**Comment by andrewoodleyjr** [comment]
+1
