### ISSUE TITLE
Doesn't work with WKWebviews (iOS)

### ISSUE THREAD

**Issue by jayniz** [EddyVerbruggen/Custom-URL-scheme#78]
This plugin doesn't work when using [WKWebviews](https://github.com/Telerik-Verified-Plugins/WKWebView) - did anybody play around with this?

Edit: see [WKWebview plugin issue](https://github.com/Telerik-Verified-Plugins/WKWebView/issues/98)

**Comment by EddyVerbruggen** [comment]
Hi, this is an issue with the other plugin. Which I will fix.

**Comment by jayniz** [comment]
@EddyVerbruggen

![](https://dl.dropboxusercontent.com/u/1953503/gifs/TBlksFs.gif)

Let me know if I can be of any help and/or test stuff!

**Comment by EddyVerbruggen** [comment]
Lol :)

Go ahead, download the WKWebView 0.3.7 release!

**Comment by jayniz** [comment]
Done so, works like a charm. Thanks!

On Mon, Apr 20, 2015 at 9:13 PM, Eddy Verbruggen <notifications@github.com>
wrote:

> Lol :)
>
> Go ahead, download the WKWebView 0.3.7 release!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EddyVerbruggen/Custom-URL-scheme/issues/78#issuecomment-94544655>
> .
>



-- 
✉ jannis hermanns · prenzlauer allee 32 · 10405 berlin · germany     »
http://jann.is
_______________________________________________________________________________
Never argue with idiots.
They drag you down to their level and beat you with experience.
