### ISSUE TITLE
Cleanly Change a URI scheme

### ISSUE THREAD

**Issue by wdietz** [EddyVerbruggen/Custom-URL-scheme#80]
I use this plugin in an app created with Ionic.
I am building locally and testing this on an Android Nexus 7 via USB debugging.
 
When I first installed the plugin I used a URI of myfirstscheme but then I later wanted to change it to mysecondscheme.

To change this I first just searched my project for myfirstscheme and changed it to mysecondscheme, this didn't work.
Next I tried uninstalling the plugin and reinstalling using the new scheme, this did associate the new URI scheme but the old scheme was not removed.
Next I tried removing and reinstalling my app but the old binding was still there.

Now my app is bound to both schemes, is there a way to remove the old binding?

**Comment by EddyVerbruggen** [comment]
If you tried uninstalling it first (not manually editing the project and then uninstalling it) then I think it would have been removed nicely.

You should now open AndroidManifest.xml and remove the incorrect duplicate block here: https://github.com/EddyVerbruggen/Custom-URL-scheme/blob/master/plugin.xml#L63-L68

**Comment by wdietz** [comment]
Thanks for the quick response.
Based on your advice I just added the plugin back with the first scheme, then uninstalled the plugin and installed it again with the new scheme and it worked as expected.
