### ISSUE TITLE
Gmail removing the href:"myapp://"

### ISSUE THREAD

**Issue by sebastiandanilonr** [EddyVerbruggen/Custom-URL-scheme#81]
Hello there.
I'm trying to send and email with a link that will open  my application. But Gmail is deleting the href="myapp://" from the <a> element on the HTML of the message. 
¿Did anyone solve this or knows a solution?
Thanks.

**Comment by Thorazine** [comment]
Yes, some online research has determined that Gmail indeed destroys these links when it doesn't fit their security profile (even with http links).
To get around it I just made a web page with a redirect. Thus putting a normal http link in the email with the variables I require for the app, and then Js redirecting the client to the [custom_url_scheme]:// link.
This method has the added bonus of being able to filter the non-mobile users. Cause obviously email can be opened on multiple devices.

**Comment by kaansoral** [comment]
When I first saw this thread, I remembered experiencing the issue myself, but couldn't remember my solution, now I recalled that it's the same with Thorazine's

It's a good idea to put all the logic to web, you can also check the existence of the app from the url scheme as far as I remember, it might be a hacky method, probably redirecting user to the app if it exists, or to ios/android app store is possible

In any case, the web capabilities definitely extend the email capabilities, as email is almost always more restrictive

**Comment by sebastiandanilonr** [comment]
Thank you for your answers. I did exactly that. It's a better solution indeed.
