### ISSUE TITLE
Meteor + Custom-URL-scheme

### ISSUE THREAD

**Issue by c316** [EddyVerbruggen/Custom-URL-scheme#82]
Any idea how to make this plugin work in Meteor? I have it launching the app, but the path and the query_string aren't coming over and I'm not sure how to print that or handle it. I've included this in the client/compatibility folder and tried it in the lib directory, but I never see anything printed to the console. 

Any help or hints in the right direction will be appreciated. Thanks

```
Meteor.startup(function() {
    function handleOpenURL(url) {
        console.log("received url: " + url);
    }
});
```

**Comment by alpjor** [comment]
@c316 How'd you get it working to even launch the app? I've been trying this w/ no luck:

diff --git a/.meteor/cordova-plugins b/.meteor/cordova-plugins
index dd2bd54..2935101 100644
--- a/.meteor/cordova-plugins
+++ b/.meteor/cordova-plugins
@@ -1,4 +1,5 @@
 com.phonegap.plugins.facebookconnect@https://github.com/Wizcorp/phonegap-facebook-plugin/tarball/3d52b1eb8a55ebcf8ad10c75d99deedeca0c0fdd
+nl.x-services.plugins.launchmyapp@https://github.com/EddyVerbruggen/Custom-URL-scheme/tarball/3ce0b6df0eb7115114f11b448a99648825a8db13
 org.apache.cordova.contacts@0.2.15
 org.apache.cordova.geolocation@0.3.11
 org.apache.cordova.network-information@0.2.14
diff --git a/head.html b/head.html
index ba91c34..6a69dbb 100644
--- a/head.html
+++ b/head.html
@@ -41,4 +41,9 @@
       while (index) load_script(scripts[--index]);
     };
   </script>
+  <script>
+    function handleOpenURL(url) {
+      debugger;
+    }
+  </script>
 </head>
diff --git a/mobile-config.js b/mobile-config.js
index 0e1a1ab..eb86fd3 100644
--- a/mobile-config.js
+++ b/mobile-config.js
@@ -73,3 +73,7 @@ App.configurePlugin('com.phonegap.plugins.facebookconnect', {
   APP_NAME: 'Bolt Integration'
 });
+
+App.configurePlugin('nl.x-services.plugins.launchmyapp', {
+  URL_SCHEME: 'bolt'
+});

**Comment by c316** [comment]
I'm having a really hard time trying to figure out what you've posted above. I did notice that you have the handleOpenURL function there, but it isn't a global function and isn't wrapped in Meteor.startup

Check out this issue in the iron-router github area and try this
https://github.com/iron-meteor/iron-router/issues/1330

```
Meteor.startup(function() {
    handleOpenURL = function handleOpenURL(url) {
        var token = url.replace("mygreatapp://verify-email/", "");
        console.log("Token: " + token);
        window.location.href = 'http://meteor.local/verify-email/' + token;
    }
});
```

I'm not sure if this will solve your problem though as I never did have a problem with the app launching, just what was happening after that. I had only gotten it to work on the ios emulator. I just started testing on Android and all I get is a message, "Website not available"

Please go here and +1, then add any comments you might have about your problem. 
https://github.com/EddyVerbruggen/Custom-URL-scheme/issues/74

**Comment by alpjor** [comment]
@c316 The issue has nothing to do with the Global-ness or the wrapped in Meteor.startup-ness of the handleOpenURL function (it is 100% global in this context, BTW). My issue is that when I 'meteor build ...' the resulting xcode .plist file doesn't contain the URL Scheme entry that would enable my app to be launched via a custom url scheme. If I manually add the entry to my .plist file before I compile, then things work fine, but I thought the whole point of the mobile-config.js entry was the the Meteor-Cordova build step should have taken care of this automatically. Maybe I'm mistaken? I should note that I'm also using the facebookConnectPlugin from WizCorp (https://github.com/Wizcorp/phonegap-facebook-plugin) and that plugin is successful at making the correct URL Scheme entry in the plist file for the facebook integration, so it's weird that this plugin isn't. Also to note that I've tried removing the facebook connect plugin to test if it was somehow overwriting the Custom URL Scheme plugin, but I got the same results w/o it installed.

**Comment by alpjor** [comment]
I found the code in the FacebookPlugin that does what I wanted:

in plugin.xml

```
 <config-file target="*-Info.plist" parent="CFBundleURLTypes">
          <array>
            <dict>
              <key>CFBundleURLSchemes</key>
              <array>
                <string>fb$APP_ID</string>
              </array>
            </dict>
          </array>
        </config-file>
```

trying to see where this should go in launchmyapp now...

**Comment by alpjor** [comment]
okay. I see the correct entry in the plugin.xml file, which should be appending the URL scheme in the appropriate place, but it's just not working.

```
<!-- ios -->
  <platform name="ios">
    <js-module src="www/ios/LaunchMyApp.js" name="LaunchMyApp">
      <clobbers target="window.plugins.launchmyapp" />
    </js-module>

    <config-file target="*-Info.plist" parent="CFBundleURLTypes">
      <array>
        <dict>
          <key>CFBundleURLSchemes</key>
          <array>
            <string>$URL_SCHEME</string>
          </array>
        </dict>
      </array>
    </config-file>
  </platform>
```

my current theory is that the cordova build step is erroring out somehow when installing this plugin. Trying to figure out how to debug that now.

**Comment by alpjor** [comment]
This is my issue: 
http://stackoverflow.com/questions/26886891/two-cordova-plugins-modifying-info-plist-cfbundleurltypes
https://issues.apache.org/jira/browse/CB-8007

**Comment by EddyVerbruggen** [comment]
@alpjor Ouch, thanks for pointing us at that Cordova issue. I voted.

**Comment by alpjor** [comment]
@EddyVerbruggen <wink/>

**Comment by EddyVerbruggen** [comment]
Fix seems to be coming with `cordova-lib` `5.1.x`, see https://issues.apache.org/jira/browse/CB-8007

**Comment by benjick** [comment]
@c316 how did you install the plugin? The app open but the alert never happens aka it's not triggered

**Comment by woniesong92** [comment]
@EddyVerbruggen @c316 did you get this working?

**Comment by rlech** [comment]
any updates here?
