### ISSUE TITLE
not working on cordova ios 3.8.0

### ISSUE THREAD

**Issue by roysG** [EddyVerbruggen/Custom-URL-scheme#84]
when i click on the link: (from browser)
picktags://dealId={dealId}&placeName={placeName} 

it redirect me to my app, but without all the parameters after ://

console log:
2015-05-16 20:13:15.632 picktags[1999:190440] picktags://

lastly i upgraded my cordova and then the problem started !

on android everything is ok.

If you need more information let me know.

**Comment by EddyVerbruggen** [comment]
Just tried this on an iPhone 6 with a new Cordova CLI app, see screenshot:

![img_3968](https://cloud.githubusercontent.com/assets/1426370/7667246/8b3dd73a-fc01-11e4-8f08-5f6bc3a326cc.PNG)

What's your app's source like?

**Comment by roysG** [comment]
what do u mean app's source like?

**Comment by EddyVerbruggen** [comment]
What the sourcecode of your app looks like. Can I see it somewhere to be able to assist you?

**Comment by roysG** [comment]
i follow your example:

 function handleOpenURL(url) {
        console.log(url);
    }

**Comment by EddyVerbruggen** [comment]
Please post some more. The very least would be your entire index.html.

**Comment by roysG** [comment]
instructions:

1.run new project of ionic:
ionic start myApp tabs

2. add ios platform
cordova platform add ios

3. install your plugin:
cordova plugin add https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git --variable URL_SCHEME=mycoolapp

4.put the function callback on the beginning of the app.js.

function handleOpenURL(url) {
  console.log("received url: " + url);
}

5. build and run the app. 
 5.1 Try to click on the link from browser and you see in the console, you will get:

2015-05-16 23:03:53.337 myApp[414:29835] received url: mycoolapp://

**Comment by EddyVerbruggen** [comment]
Do these links yield the same result?
http://www.x-services.nl/launchmyapp.php

**Comment by roysG** [comment]
i am sorry, the plugin works perfectly with cordova ios 3.8. :)
I found the problem in my side.

**Comment by roysG** [comment]
i was problem with hebrew, i jus was needed to encode the text before sending it :+1:
