### ISSUE TITLE
Did Phonegap Build break Custom Urls on iOS?

### ISSUE THREAD

**Issue by benmcmaster** [EddyVerbruggen/Custom-URL-scheme#85]
As of a few days ago, custom URLs are not working from my Phonegap Build iOS app. No code has changed on my end.

When I open the .ipa from 10 days ago, and I check the info.plist, we have in `URL types`:
```xml
<array>
    <dict>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>vimify</string>
        </array>
    </dict>
    <dict>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>fb545649333125539</string>
        </array>
    </dict>
</array>
```

And today the `URL types` is an empty array:
```xml
<array/>
```
This makes sense because my facebook plugin isn't opening the native facebook app either.

Is anyone seeing this on Phonegap Build?

**Comment by redbird19** [comment]
Yep, I'm seeing the same thing here.  My app uses the Custom URL scheme plugin (https://build.phonegap.com/plugins/844) as well as the Facebook Connect plugin (https://build.phonegap.com/plugins/1246).  Both were working a while back, and I haven't modified any of the code or settings for either, but now my url links do NOT work, and my Facebook login screen is NOT using the native app either....very frustrating....

**Comment by benmcmaster** [comment]
@redbird19, I also raised the issue here: 

http://community.phonegap.com/nitobi/topics/did-the-latest-release-of-phonegap-build-break-custom-urls-in-ios

**Comment by benmcmaster** [comment]
Hmm. That was quick looks like PGB secretly fixed the issue. Custom Urls are now working in my latest PGB build.
