### ISSUE TITLE
launchmyapp + dropboxchoosert, is problem on iOS.

### ISSUE THREAD

**Issue by kevinblade** [EddyVerbruggen/Custom-URL-scheme#87]
Hi!
I have used launchmyapp and dropboxchooser on Android very well.
Recently, I am trying to use on iOS with both. 
But, launchmyapp is not working normally. I discovered something that is not called handleOpenURL function from launchmyapp.
As I know the launchmyapp and the dropboxchoouser are used custom URL scheme is that a problem?
Help me please. How can I fix it?
Thanks

**Comment by EddyVerbruggen** [comment]
Yeah that's been an issue for a while now. And it was finally fixed 6 days ago - see https://issues.apache.org/jira/browse/CB-8007

The component is cordova-lib but there is no fix version, so I can't tell when it will be released.
