### ISSUE TITLE
LaunchMyApp.js is not automatically copied into any www or js folders when installed

### ISSUE THREAD

**Issue by symbiat** [EddyVerbruggen/Custom-URL-scheme#89]
Im following the docs to add the plugin to my Cordova project and specify a custom URL scheme on the command-line.

Your docs specifically say: 

> The LaunchMyApp.js file is brought in automatically.

But looking through my project I still see it buried in a platform-specific folder:

    $ find . -name LaunchMyApp.js
    ./platforms/android/assets/www/plugins/nl.x-services.plugins.launchmyapp/www/android/LaunchMyApp.js
    ./plugins/nl.x-services.plugins.launchmyapp/www/android/LaunchMyApp.js
    ./plugins/nl.x-services.plugins.launchmyapp/www/ios/LaunchMyApp.js
    ./plugins/nl.x-services.plugins.launchmyapp/www/windows/LaunchMyApp.js

which means you can't use the same URL in the top-level `index.html` file to reference `LaunchMyApp.js` without manually copying the file over for each platform (or having some way to build a platform-specific URL in `index.html`). This could/should probably be automated in plugin.xml ?

**Comment by EddyVerbruggen** [comment]
Just ran a quick test, this is the output after running `cordova prepare`:
```
localhost:launchtest eddyverbruggen$ find . -name LaunchMyApp.js
./platforms/android/assets/www/plugins/nl.x-services.plugins.launchmyapp/www/android/LaunchMyApp.js
./platforms/ios/www/plugins/nl.x-services.plugins.launchmyapp/www/ios/LaunchMyApp.js
./plugins/nl.x-services.plugins.launchmyapp/www/android/LaunchMyApp.js
./plugins/nl.x-services.plugins.launchmyapp/www/ios/LaunchMyApp.js
./plugins/nl.x-services.plugins.launchmyapp/www/windows/LaunchMyApp.js
```

Looks the same :+1: 

You don't need to reference those plugins because cordova.js (which is in the root of your project and referenced from your index.html, right?) loads cordova_plugins.js which has the reference to the correct plugin js file.

**Comment by symbiat** [comment]
I thought maybe it wasn't loading because Im getting this error when I try to launch the app with my custom URL:

    Uncaught ReferenceError: handleOpenURL is not defined

What should be the path referenced in `index.html` then ?

**Comment by EddyVerbruggen** [comment]
I'm assuming iOS?

Try and add this somewhere near the top of your index.html:

```js
<script>
<!-- include me as soon as possible -->
function handleOpenURL(url) {
  setTimeout(function() {
    alert("received url: " + url);
  }, 0);
}
</script>
```

**Comment by symbiat** [comment]
Ah, I need to define that properly. Im on Android (using [Ionic](http://ionicframework.com) so Im building this in AngularJS). In `app.js`, I had a typo which I have fixed (now the app launches and Im not transitioning to the correct state but I dont think that has anything to do with your plugin).

You might be interested in this alternate technique using sticky events instead of timeouts - see this article [Deep linking in Ionic Mobile Applications](https://medium.com/angularjs-articles/deep-linking-in-ionic-mobile-applications-44d8b4685bb3). Actually would love to hear what you think of it.

Thanks for the fast response BTW :+1:

**Comment by cdibened** [comment]
I think this issue can be marked as resolved/closed.

**Comment by cdibened** [comment]
Your on the ball Eddy...;)

Appreciate all your work on these plugins.  👍
