### ISSUE TITLE
Attempted to send a second callback for ID: LaunchMyApp  Result was: "Invalid action"

### ISSUE THREAD

**Issue by HectorMeneses333** [EddyVerbruggen/Custom-URL-scheme#90]
Hi Eddy,

I hope you can help me with this... 
I'm having trouble making the LaunchMyApp plugin to work for my cordova app...

I am using visual studio 2015 rc with cordova 5.1.1. I also have android sdk tools 24.2.0 as the sdk 24.3 was having issues compiling the code and I'm running with an LG Nexus 5.

I'm receiving the following error:

W/CordovaPlugin(15536): Attempted to send a second callback for ID: LaunchMyApp1588946822
W/CordovaPlugin(15536): Result was: "Invalid action"

I can't make the plugin to really open my app...I tried testing from chrome by entering my url scheme in the address window (  myappurlscheme:// )
I assume the error above is the source of the problem.

I also tried creating another app and calling window.open('myappurlscheme://','_system');

Thanks a bunch!

Hector

**Comment by EddyVerbruggen** [comment]
Hi, can you try a webpage with a link? Just host the webpage anywhere your mobile browser can access it, then click the link. If that doesn't work I'll dive into this.

**Comment by HectorMeneses333** [comment]
Hi Eddy,
Thanks for the quick reply...
I tried the link in a browser... chrome basically says that the webpage is not available...

I'm not sure what I did but now I'm not even seeing the Invalid Action message.

I tried reading the plugin using this command:
c:\Projects\SoldHomeAlert\SoldHomeAlert>npm install -g cordova cordova plugin add nl.x-services.plugins.launchmyapp --variable URL_SCHEME=soldhomealerturlscheme

then I get this error:


npm ERR! 404 404 Not Found: nl.x-services.plugins.launchmyapp
npm ERR! 404
npm ERR! 404 'nl.x-services.plugins.launchmyapp' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "cordova" "plugin" "add" "nl.x-services.pl
ugins.launchmyapp" "--variable" "URL_SCHEME=soldhomealerturlscheme"
npm ERR! cwd c:\Projects\SoldHomeAlert\SoldHomeAlert
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\Projects\SoldHomeAlert\SoldHomeAlert\npm-debug.log
npm ERR! not ok code 0

I also tried just the following:
cordova plugin add nl.x-services.plugins.launchmyapp --variable URL_SCHEME=soldhomealerturlscheme

This seems to add the plugin but when I debug the app from visual studio I don't see any indication that the plugin is getting hooked at all...

If then I use the config.xml dialog in visual studio, the plugin seems to be installed correctly but when I compile I get this error:

1>  ------ Currently configured plugins: org.apache.cordova.inappbrowser@0.6.0,cordova-plugin-legacy-whitelist@1.0.1-dev,nl.x-services.plugins.launchmyapp@3.2.2
1>  ------ Adding plugin: nl.x-services.plugins.launchmyapp@3.2.2
1>  Calling plugman.fetch on plugin "nl.x-services.plugins.launchmyapp@3.2.2"
1>  Fetching plugin "nl.x-services.plugins.launchmyapp@3.2.2" via cordova plugins registry
1>  Copying plugin "C:\Users\Hector\.plugman\cache\nl.x-services.plugins.launchmyapp\3.2.2\package" => "c:\Projects\Cordova\SoldHomeAlert\SoldHomeAlert\plugins\nl.x-services.plugins.launchmyapp"
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

then I can't run the app...

Thanks again for your help!!!

**Comment by symbiat** [comment]
@HectorMeneses333 Did you try installing using the Git URL instead of the name? i.e.

`cordova plugin add https://github.com/EddyVerbruggen/Custom-URL-scheme.git --variable URL_SCHEME=soldhomealerturlscheme`

(That's a pretty long scheme name BTW - means your links will all start with
 `soldhomealerturlscheme://`...

**Comment by EddyVerbruggen** [comment]
@HectorMeneses333 use the add method @HectorMeneses333 showed, that should always work.

Do you guys by any chance have the whitelist plugin configured and also a CSP meta tag? That may block the inline script from running.

**Comment by symbiat** [comment]
@EddyVerbruggen Do I need to configure add the whitelist plugin if Im running Cordova 4.3 ?

**Comment by EddyVerbruggen** [comment]
@symbiat No you don't need to. It's just something that would possibly clash with inline scripts. If you don't have it you can ignore my previous comment.

**Comment by symbiat** [comment]
@EddyVerbruggen Correction: the CLI is 4.3.0 but my Cordova lib is 3.7.1.

**Comment by EddyVerbruggen** [comment]
This is my entire `index.html` of the vanilla CLI generated Cordova project, perhaps it somehow shines a light on your case:

```
<!DOCTYPE html>
<html>
    <head>
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
        <link rel="stylesheet" type="text/css" href="css/index.css">
        <title>Hello World</title>
        <script>
            function handleOpenURL(url) {
                setTimeout(function() {
                    alert("received url: " + url);
                }, 0);
            }
        </script>
    </head>
    <body>
        <div class="app">
            <h1>Apache Cordova</h1>
            <div id="deviceready" class="blink">
                <p class="event listening">Connecting to Device</p>
                <p class="event received">Device is Ready</p>
            </div>
        </div>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="js/index.js"></script>
    </body>
</html>
```

I've added the plugin with custom url scheme `mycoolapp`, and opened [this page](http://www.x-services.nl/launchmyapp.php) on my mobile Chrome browser (Android 4.4 in this case).

After clicking one of the 'mycoolapp://..' links the app launched and the alert popup showed.

**Comment by symbiat** [comment]
@EddyVerbruggen Ive been using the technique outlined in https://medium.com/angularjs-articles/deep-linking-in-ionic-mobile-applications-44d8b4685bb3 so in `app.js` I have:
```
if ('cordova' in window) {                                                      
    // create a sticky event for handling the app being opened via a custom URL 
    cordova.addStickyDocumentEventHandler("handleopenurl");                     
}                                                                               
                                                                                
function handleOpenURL (url) {                                                  
    console.log('DEEP LINK URL: ' + url);                                       
    cordova.fireDocumentEvent("handleopenurl", { url: url });                   
}  
```
This was working last week but I subsequently had to remove/re-add platforms so all plugins were reinstalled. I can veryify that the correct files are present under `platforms/android/assets`.

**Comment by EddyVerbruggen** [comment]
@symbiat can you please share your Android platform project with me? This is just guessing for me otherwise..

**Comment by symbiat** [comment]
@EddyVerbruggen Not sure if that would be possible - or do you just need the platform folder ?

**Comment by EddyVerbruggen** [comment]
Yeah, the plaforms/android folder would suffice, you can email it to eddyverbruggen at gmail

**Comment by symbiat** [comment]
@EddyVerbruggen Sharing from Google Drive. Not sure if this will build / run but at least you'll be able to look at the code. We're using Ionic

**Comment by HectorMeneses333** [comment]
@EddyVerbruggen @symbiat 
I was able to make my build work finally...

My configuration goes as this:
Visual Studio 2015 RC
npm 1.4.28
cordova 5.1.1
I also have a MacBook with 
npm 2.10.1
cordova 5.1.1

1. I added the Custom URL Scheme plugin this way:
cordova plugin add nl.x-services.plugins.launchmyapp --variable URL_SCHEME=soldhomealerturlscheme

2. Modified the plugin.xml file under nl.x-services.plugins.launchmyapp 
- 
- Replaced $URL_SCHEME with my own urlscheme: soldhomealerturlscheme
- I know this is a hack ... but I'm more interested in the result versus the elegance of the solution. I believe the Visual Studio 2015 team will fix this at some point as it seems like they are not passing the correct variables to plugman.

3. This step kept failing in Visual Studio so I decided to run it in a cmd. 
"{Your User Folder}\AppData\Roaming\npm\\node_modules\vs-tac\vs-tac-cli.cmd" build --platform Android --configuration Debug --projectDir . --projectName SoldHomeAlert --npmInstallDir C:\Users\Hector\AppData\Roaming\npm --language en-US --buildServerUrl https://172.17.64.43:3000 --buildTarget AndroidDevice

After that the plugin got installed correctly and it is actually able to process requests for soldhomealerturlscheme:// and soldhomealerturlscheme://?param1=value1&param2=value2  ...etc

Hector

**Comment by HectorMeneses333** [comment]
step 3... actually should say that I commented out <preference name="URL_SCHEME" /> in the plugin.xml file. 
ohh... also in config.xml at  the project root level I commented out:
    <param name="URL_SCHEME" value="soldhomealerturlscheme" />

In that way plugman does not think that the variable is needed....

**Comment by HectorMeneses333** [comment]
hmm.... weird... the editor keeps taking my comments away...

step 3... actually should say that I commented out in the plugin.xml file.
                preference name="URL_SCHEME"
ohh... also in config.xml at the project root level I commented out:
                param name="URL_SCHEME" value="soldhomealerturlscheme"


In that way plugman does not think that the variable is needed....

**Comment by EddyVerbruggen** [comment]
This should be history with the latest 4.0.0 release.
