### ISSUE TITLE
iOs build NOT WORKING

### ISSUE THREAD

**Issue by xale76** [EddyVerbruggen/Custom-URL-scheme#94]
I use Intel XDK cordova.
I built my app with this plugin. Entering myapp:// on browser works fine in android: my app regulary starts. The same not working on iOs: nothing starts.
What's the problem?
Thank you

**Comment by xale76** [comment]
I found the problem: I have installed your facebook plugin too. Both try to changhe .plist file so only the first is able to change it (should do it both, and add 2 keys in URL Scheme node).

**Comment by theblanchard** [comment]
I'm having this issue as well, using the Social Sharing plugin. Is this a known bug, possible fix on the way?

**Comment by kaansoral** [comment]
Yes it's known, the reason this still exists is because the fix from the cordova side still hasn't reached production after months, so it's cordova's fault, you can all just simply add the url scheme to .plist yourselves for the time being

**Comment by theblanchard** [comment]
Good to know! And thanks for the quick response.

**Comment by xale76** [comment]
Thank You...but what about the problem that handleOpenURL not firing on iOS cold start?

**Comment by lorensr** [comment]
For anyone else wondering, here's how to add to plist:

![image](https://cloud.githubusercontent.com/assets/251288/8535557/de5ae062-2414-11e5-87ec-3b03301c26d5.png)

click + at bottom, then eg "uber" under "URL Schemes" to get "uber://" working.
