### ISSUE TITLE
Make plugin available on npm

### ISSUE THREAD

**Issue by alexbuijs** [EddyVerbruggen/Custom-URL-scheme#95]
Hi Eddy, could you make this plugin available on npm please? That would make updating the plugin and keeping track of updates much easier. Thanks!

**Comment by alexbuijs** [comment]
perhaps as cordova-plugin-custom-url-scheme?

**Comment by EddyVerbruggen** [comment]
Hey Alex, good suggestions, I'll do it soon!

**Comment by emilbayes** [comment]
Ping :wink:

**Comment by EddyVerbruggen** [comment]
Thanks for your patience, [it's up!](https://www.npmjs.com/package/cordova-plugin-customurlscheme) :sunglasses:

**Comment by alexbuijs** [comment]
Awesome! :smiley:
