### ISSUE TITLE
Cannot Find Symbol org.apache.cordova.CordovaActivity.

### ISSUE THREAD

**Issue by blanedaze** [EddyVerbruggen/Custom-URL-scheme#96]
I just encountered this error while building in Supersonic Appgyver app, here's the log:

:modules:AGCordova:compileReleaseJava/Users/administrator/app-builder/STAGING/client/modules/AGCordova/src/nl/xservices/plugins/LaunchMyApp.java:5: error: cannot find symbol
import org.apache.cordova.CordovaActivity;
                         ^
  symbol:   class CordovaActivity
  location: package org.apache.cordova
/Users/administrator/app-builder/STAGING/client/modules/AGCordova/src/nl/xservices/plugins/LaunchMyApp.java:23: error: cannot find symbol
      final Intent intent = ((CordovaActivity) this.webView.getContext()).getIntent();
                              ^
  symbol:   class CordovaActivity
  location: class LaunchMyApp
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':modules:AGCordova:compileReleaseJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by EddyVerbruggen** [comment]
You must be missing `CordovaLib`. You'd better ask at the Apgyver forums because I don't even know how to spell it.
