### ISSUE TITLE
handleOpenURL not firing on cold start on Android with Meteor framework

### ISSUE THREAD

**Issue by Exilz** [EddyVerbruggen/Custom-URL-scheme#98]
I am building an app with Meteor and Cordova 5.0, my devices are on Android 5.1 and 4.3.
I can't figure out a way to trigger the handleOpenURL function if the app wasn't launched before calling the custom scheme. The app is still launched, though.

If the app is already launched and in background, it works fine.

I'm simply using

    handleOpenURL = function handleOpenURL(url) {
        var view = url.replace("totems://", "");
        Router.go(view);
    };

(it defers a little from the example since it's a Meteor tweak).
It looks like it's the same issue as #93 on iOS.

**Comment by benjick** [comment]
Same with the iOS simulator

**Comment by bd-arc** [comment]
I am experiencing the same issue, which unfortunately questions the point of the entire plugin...

I've already used it before, and, back then, everything was working as expected. Does anyone have a clue about the reason for this change?

**Comment by EddyVerbruggen** [comment]
@bd-arc yeah of course that would render the plugin rather useless. Shall we focus on finding the problem? Please send me the simplest possible Cordova project where it's not working for you and I'll gladly take a look.

**Comment by bd-arc** [comment]
@EddyVerbruggen Thank you very much for taking the time! Unfortunately, I deduced from your answer in issue #93 that Meteor (which I am using) might very well be part of the problem.

I will try and create a simple project without Meteor and let you know if this works as expected.

**Comment by Exilz** [comment]
Ok, so I tried to reproduce the bug on a blank cordova project with : cordova 5.0.0, crosswalk and the latest version of your plugin.
The function is triggered even on a cold start, so this issue isn't about your plugin but more about how to use it properly with Meteor.
Sadly, I guess you won't help us since it's not directly related to you, but feel free to take a look at this marvellous framework. ;)

**Comment by bd-arc** [comment]
@Exilz I can confirm your findings...

@EddyVerbruggen Sorry for having bothered you, as it is clearly a Meteor issue. I will keep you informed if I ever find a fix.

**Comment by patte** [comment]
@bd-arc @Exilz I'm stumbling upon the same problem. any chance you too have more information to make it work with meteor?

**Comment by patte** [comment]
alright, I made it work with the following workaround https://github.com/EddyVerbruggen/Custom-URL-scheme/compare/master...patte:master
I save the incoming intent string in lastIntent and I  added a function getLastIntent, which you can call from meteor like this:
```
    window.plugins.launchmyapp.getLastIntent( (intent)->
      if intent.indexOf 'myawesomeapp://' > -1
        # handle intent
      else
        console.log "ignore intent: #{intent}"
    , (error) ->
      console.log "no intent received"
    )
```
