### ISSUE TITLE
How do i use this plugin with Ionic Framework? 

### ISSUE THREAD

**Issue by aq1** [EddyVerbruggen/Custom-URL-scheme#99]
Is it even possible? I did everything that this article says but get only error (on picture).
Or maybe this plugin doesn't work in emulator? Thank you.
![screenshot from 2015-07-13 13 19 56](https://cloud.githubusercontent.com/assets/3045638/8647578/df6ceba6-2961-11e5-8d02-0166120fe6ea.png)

**Comment by aq1** [comment]
http://mcgivery.com/using-custom-url-schemes-ionic-framework-app/ forgot the link to the article.

**Comment by EddyVerbruggen** [comment]
Every Android app can have a custom url scheme, and you can use it in the emulator.

Please check your AndroidManifest.xml, it should contain your `ionicapp://` scheme. If not, reinstall the plugin, build your app and deploy it again.

**Comment by aq1** [comment]
Hello Eddy. This is very quick answer. 
And i just found the problem. Turned out it was only emulator problem. Browser in emulator to be more precisely. So it works just as it should  and you can close this issue. Thanks again.
